// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("temporalcloud");

/**
 * If set to True, it allows for an insecure connection to the Temporal Cloud API. This should never be set to 'true' in production and defaults to false.
 */
export declare const allowInsecure: boolean | undefined;
Object.defineProperty(exports, "allowInsecure", {
    get() {
        return __config.getObject<boolean>("allowInsecure") ?? utilities.getEnvBoolean("TEMPORAL_CLOUD_ALLOW_INSECURE");
    },
    enumerable: true,
});

/**
 * The ID of the account to operate on. Prevents accidental mutation of accounts other than that provided.
 */
export declare const allowedAccountId: string | undefined;
Object.defineProperty(exports, "allowedAccountId", {
    get() {
        return __config.get("allowedAccountId") ?? utilities.getEnv("TEMPORAL_CLOUD_ALLOWED_ACCOUNT_ID");
    },
    enumerable: true,
});

/**
 * The API key for Temporal Cloud. See [this documentation](https://docs.temporal.io/cloud/api-keys) for information on how to obtain an API key.
 */
export declare const apiKey: string | undefined;
Object.defineProperty(exports, "apiKey", {
    get() {
        return __config.get("apiKey") ?? utilities.getEnv("TEMPORAL_CLOUD_API_KEY");
    },
    enumerable: true,
});

/**
 * The endpoint for the Temporal Cloud API. Defaults to `saas-api.tmprl.cloud:443`.
 */
export declare const endpoint: string | undefined;
Object.defineProperty(exports, "endpoint", {
    get() {
        return __config.get("endpoint") ?? utilities.getEnv("TEMPORAL_CLOUD_ENDPOINT");
    },
    enumerable: true,
});

