// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface AccountAuditLogSinkKinesis {
    /**
     * The destination URI of the Kinesis stream where Temporal will send data.
     */
    destinationUri: pulumi.Input<string>;
    /**
     * The region of the Kinesis stream.
     */
    region: pulumi.Input<string>;
    /**
     * The IAM role that Temporal Cloud assumes for writing records to the customer's Kinesis stream.
     */
    roleName: pulumi.Input<string>;
}

export interface AccountAuditLogSinkPubsub {
    /**
     * The GCP project ID of the PubSub topic and service account.
     */
    gcpProjectId?: pulumi.Input<string | undefined>;
    /**
     * The service account email associated with the PubSub topic and service account.
     */
    serviceAccountEmail?: pulumi.Input<string | undefined>;
    /**
     * The customer service account ID that Temporal Cloud impersonates for writing records to the customer's PubSub topic.
     */
    serviceAccountId?: pulumi.Input<string | undefined>;
    /**
     * The destination PubSub topic name for Temporal.
     */
    topicName: pulumi.Input<string>;
}

export interface AccountAuditLogSinkTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: pulumi.Input<string | undefined>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: pulumi.Input<string | undefined>;
}

export interface ApikeyTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: pulumi.Input<string | undefined>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: pulumi.Input<string | undefined>;
}

export interface ConnectivityRuleTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: pulumi.Input<string | undefined>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: pulumi.Input<string | undefined>;
}

export interface GetNamespaceCertificateFilter {
    /**
     * The certificate's common name.
     */
    commonName?: string;
    /**
     * The certificate's organization.
     */
    organization?: string;
    /**
     * The certificate's organizational unit.
     */
    organizationalUnit?: string;
    /**
     * The certificate's subject alternative name (or SAN).
     */
    subjectAlternativeName?: string;
}

export interface GetNamespaceCertificateFilterArgs {
    /**
     * The certificate's common name.
     */
    commonName?: pulumi.Input<string | undefined>;
    /**
     * The certificate's organization.
     */
    organization?: pulumi.Input<string | undefined>;
    /**
     * The certificate's organizational unit.
     */
    organizationalUnit?: pulumi.Input<string | undefined>;
    /**
     * The certificate's subject alternative name (or SAN).
     */
    subjectAlternativeName?: pulumi.Input<string | undefined>;
}

export interface GetNamespaceCodecServer {
    /**
     * The endpoint of the codec server.
     */
    endpoint?: string;
    /**
     * If true, Temporal Cloud will include cross-origin credentials in requests to the codec server.
     */
    includeCrossOriginCredentials?: boolean;
    /**
     * If true, Temporal Cloud will pass the access token to the codec server upon each request.
     */
    passAccessToken?: boolean;
}

export interface GetNamespaceCodecServerArgs {
    /**
     * The endpoint of the codec server.
     */
    endpoint?: pulumi.Input<string | undefined>;
    /**
     * If true, Temporal Cloud will include cross-origin credentials in requests to the codec server.
     */
    includeCrossOriginCredentials?: pulumi.Input<boolean | undefined>;
    /**
     * If true, Temporal Cloud will pass the access token to the codec server upon each request.
     */
    passAccessToken?: pulumi.Input<boolean | undefined>;
}

export interface GetNamespacePrivateConnectivity {
    /**
     * The AWS PrivateLink info. This will only be set for namespaces whose cloud provider is AWS.
     */
    awsPrivateLinkInfo?: inputs.GetNamespacePrivateConnectivityAwsPrivateLinkInfo;
    /**
     * The id of the region where the private connectivity applies.
     */
    region?: string;
}

export interface GetNamespacePrivateConnectivityArgs {
    /**
     * The AWS PrivateLink info. This will only be set for namespaces whose cloud provider is AWS.
     */
    awsPrivateLinkInfo?: pulumi.Input<inputs.GetNamespacePrivateConnectivityAwsPrivateLinkInfoArgs | undefined>;
    /**
     * The id of the region where the private connectivity applies.
     */
    region?: pulumi.Input<string | undefined>;
}

export interface GetNamespacePrivateConnectivityAwsPrivateLinkInfo {
    /**
     * The list of principal arns that are allowed to access the namespace on the private link.
     */
    allowedPrincipalArns?: string[];
    /**
     * The list of vpc endpoint service names that are associated with the namespace.
     */
    vpcEndpointServiceNames?: string[];
}

export interface GetNamespacePrivateConnectivityAwsPrivateLinkInfoArgs {
    /**
     * The list of principal arns that are allowed to access the namespace on the private link.
     */
    allowedPrincipalArns?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The list of vpc endpoint service names that are associated with the namespace.
     */
    vpcEndpointServiceNames?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

export interface GetServiceAccountNamespaceAccess {
    /**
     * The namespace to assign permissions to.
     */
    namespaceId?: string;
    /**
     * The permission to assign. Must be one of admin, write, or read (case-insensitive).
     */
    permission?: string;
}

export interface GetServiceAccountNamespaceAccessArgs {
    /**
     * The namespace to assign permissions to.
     */
    namespaceId?: pulumi.Input<string | undefined>;
    /**
     * The permission to assign. Must be one of admin, write, or read (case-insensitive).
     */
    permission?: pulumi.Input<string | undefined>;
}

export interface GetUserNamespaceAccess {
    /**
     * The namespace to assign permissions to.
     */
    namespaceId?: string;
    /**
     * The permission to assign. Must be one of admin, write, or read (case-insensitive)
     */
    permission?: string;
}

export interface GetUserNamespaceAccessArgs {
    /**
     * The namespace to assign permissions to.
     */
    namespaceId?: pulumi.Input<string | undefined>;
    /**
     * The permission to assign. Must be one of admin, write, or read (case-insensitive)
     */
    permission?: pulumi.Input<string | undefined>;
}

export interface GroupAccessNamespaceAccess {
    /**
     * The namespace to assign permissions to.
     */
    namespaceId: pulumi.Input<string>;
    /**
     * The permission to assign. Must be one of admin, write, or read (case-insensitive)
     */
    permission: pulumi.Input<string>;
}

export interface GroupMembersTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: pulumi.Input<string | undefined>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: pulumi.Input<string | undefined>;
}

export interface GroupTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: pulumi.Input<string | undefined>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: pulumi.Input<string | undefined>;
}

export interface MetricsEndpointTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: pulumi.Input<string | undefined>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: pulumi.Input<string | undefined>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    update?: pulumi.Input<string | undefined>;
}

export interface NamespaceCapacity {
    /**
     * The mode of the capacity configuration. Must be one of 'provisioned' or 'on_demand'.
     */
    mode?: pulumi.Input<string | undefined>;
    /**
     * The value of the capacity configuration. Must be set when mode is 'provisioned'.
     */
    value?: pulumi.Input<number | undefined>;
}

export interface NamespaceCertificateFilter {
    /**
     * The certificate's common name.
     */
    commonName?: pulumi.Input<string | undefined>;
    /**
     * The certificate's organization.
     */
    organization?: pulumi.Input<string | undefined>;
    /**
     * The certificate's organizational unit.
     */
    organizationalUnit?: pulumi.Input<string | undefined>;
    /**
     * The certificate's subject alternative name (or SAN).
     */
    subjectAlternativeName?: pulumi.Input<string | undefined>;
}

export interface NamespaceCodecServer {
    /**
     * The endpoint of the codec server. Must begin with "https".
     */
    endpoint: pulumi.Input<string>;
    /**
     * If true, Temporal Cloud will include cross-origin credentials in requests to the codec server.
     */
    includeCrossOriginCredentials?: pulumi.Input<boolean | undefined>;
    /**
     * If true, Temporal Cloud will pass the access token to the codec server upon each request.
     */
    passAccessToken?: pulumi.Input<boolean | undefined>;
}

export interface NamespaceEndpoints {
    /**
     * The gRPC address for API key client connections (may be empty if API keys are disabled).
     */
    grpcAddress?: pulumi.Input<string | undefined>;
    /**
     * The gRPC address for mTLS client connections (may be empty if mTLS is disabled).
     */
    mtlsGrpcAddress?: pulumi.Input<string | undefined>;
    /**
     * The address in the Temporal Cloud Web UI for the namespace
     */
    webAddress?: pulumi.Input<string | undefined>;
}

export interface NamespaceExportSinkGcs {
    /**
     * The name of the destination GCS bucket where Temporal will send data.
     */
    bucketName: pulumi.Input<string>;
    /**
     * The GCP project ID associated with the GCS bucket and service account. If not provided, the service*account*email must be provided.
     */
    gcpProjectId?: pulumi.Input<string | undefined>;
    /**
     * The region of the gcs bucket
     */
    region: pulumi.Input<string>;
    /**
     * The service account email associated with the GCS bucket and service account. If not provided, the service*account*id and gcp*project*id must be provided.
     */
    serviceAccountEmail?: pulumi.Input<string | undefined>;
    /**
     * The customer service account ID that Temporal Cloud impersonates for writing records to the customer's GCS bucket. If not provided, the service*account*email must be provided.
     */
    serviceAccountId?: pulumi.Input<string | undefined>;
}

export interface NamespaceExportSinkS3 {
    /**
     * The AWS account ID associated with the S3 bucket and the assumed role.
     */
    awsAccountId: pulumi.Input<string>;
    /**
     * The name of the destination S3 bucket where Temporal will send data.
     */
    bucketName: pulumi.Input<string>;
    /**
     * The AWS Key Management Service (KMS) ARN used for encryption.
     */
    kmsArn?: pulumi.Input<string | undefined>;
    /**
     * The region where the S3 bucket is located.
     */
    region: pulumi.Input<string>;
    /**
     * The IAM role that Temporal Cloud assumes for writing records to the customer's S3 bucket.
     */
    roleName: pulumi.Input<string>;
}

export interface NamespaceExportSinkTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: pulumi.Input<string | undefined>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: pulumi.Input<string | undefined>;
}

export interface NamespaceNamespaceLifecycle {
    /**
     * If true, the namespace cannot be deleted. This is a safeguard against accidental deletion. To delete a namespace with this option enabled, you must first set it to false.
     */
    enableDeleteProtection?: pulumi.Input<boolean | undefined>;
}

export interface NamespaceTagsTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: pulumi.Input<string | undefined>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: pulumi.Input<string | undefined>;
}

export interface NamespaceTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: pulumi.Input<string | undefined>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: pulumi.Input<string | undefined>;
}

export interface NexusEndpointTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: pulumi.Input<string | undefined>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: pulumi.Input<string | undefined>;
}

export interface NexusEndpointWorkerTarget {
    /**
     * The target cloud namespace to route requests to. Namespace must be in same account as the endpoint.
     */
    namespaceId: pulumi.Input<string>;
    /**
     * The task queue on the cloud namespace to route requests to.
     */
    taskQueue: pulumi.Input<string>;
}

export interface ServiceAccountNamespaceAccess {
    /**
     * The namespace to assign permissions to.
     */
    namespaceId: pulumi.Input<string>;
    /**
     * The permission to assign. Must be one of admin, write, or read (case-insensitive)
     */
    permission: pulumi.Input<string>;
}

export interface ServiceAccountNamespaceScopedAccess {
    /**
     * The namespace to scope this service account to. This field is immutable after creation.
     */
    namespaceId: pulumi.Input<string>;
    /**
     * The permission to assign. Must be one of admin, write, or read (case-insensitive). This field is mutable.
     */
    permission: pulumi.Input<string>;
}

export interface ServiceAccountTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: pulumi.Input<string | undefined>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: pulumi.Input<string | undefined>;
}

export interface UserNamespaceAccess {
    /**
     * The namespace to assign permissions to.
     */
    namespaceId: pulumi.Input<string>;
    /**
     * The permission to assign. Must be one of admin, write, or read (case-insensitive)
     */
    permission: pulumi.Input<string>;
}

export interface UserTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: pulumi.Input<string | undefined>;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: pulumi.Input<string | undefined>;
}
