// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface AccountAuditLogSinkKinesis {
    /**
     * The destination URI of the Kinesis stream where Temporal will send data.
     */
    destinationUri: string;
    /**
     * The region of the Kinesis stream.
     */
    region: string;
    /**
     * The IAM role that Temporal Cloud assumes for writing records to the customer's Kinesis stream.
     */
    roleName: string;
}

export interface AccountAuditLogSinkPubsub {
    /**
     * The GCP project ID of the PubSub topic and service account.
     */
    gcpProjectId: string;
    /**
     * The service account email associated with the PubSub topic and service account.
     */
    serviceAccountEmail: string;
    /**
     * The customer service account ID that Temporal Cloud impersonates for writing records to the customer's PubSub topic.
     */
    serviceAccountId: string;
    /**
     * The destination PubSub topic name for Temporal.
     */
    topicName: string;
}

export interface AccountAuditLogSinkTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: string;
}

export interface ApikeyTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: string;
}

export interface ConnectivityRuleTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: string;
}

export interface GetAccountAuditLogSinkKinesis {
    /**
     * The destination URI of the Kinesis stream where Temporal will send data.
     */
    destinationUri: string;
    /**
     * The region of the Kinesis stream.
     */
    region: string;
    /**
     * The IAM role that Temporal Cloud assumes for writing records to the customer's Kinesis stream.
     */
    roleName: string;
}

export interface GetAccountAuditLogSinkPubsub {
    /**
     * The GCP project ID of the PubSub topic and service account.
     */
    gcpProjectId: string;
    /**
     * The service account email associated with the PubSub topic and service account.
     */
    serviceAccountEmail: string;
    /**
     * The customer service account ID that Temporal Cloud impersonates for writing records to the customer's PubSub topic.
     */
    serviceAccountId: string;
    /**
     * The destination PubSub topic name for Temporal.
     */
    topicName: string;
}

export interface GetNamespaceCertificateFilter {
    /**
     * The certificate's common name.
     */
    commonName: string;
    /**
     * The certificate's organization.
     */
    organization: string;
    /**
     * The certificate's organizational unit.
     */
    organizationalUnit: string;
    /**
     * The certificate's subject alternative name (or SAN).
     */
    subjectAlternativeName: string;
}

export interface GetNamespaceCodecServer {
    /**
     * The endpoint of the codec server.
     */
    endpoint: string;
    /**
     * If true, Temporal Cloud will include cross-origin credentials in requests to the codec server.
     */
    includeCrossOriginCredentials: boolean;
    /**
     * If true, Temporal Cloud will pass the access token to the codec server upon each request.
     */
    passAccessToken: boolean;
}

export interface GetNamespaceEndpoints {
    /**
     * The gRPC hostport address that the temporal workers, clients and tctl connect to.
     */
    grpcAddress: string;
    /**
     * The web UI address.
     */
    webAddress: string;
}

export interface GetNamespaceLimits {
    /**
     * The number of actions per second (APS) that is currently allowed for the namespace. The namespace may be throttled if its APS exceeds the limit.
     */
    actionsPerSecondLimit: number;
}

export interface GetNamespaceNamespaceLifecycle {
    /**
     * If true, delete protection is enabled for the namespace. This means that the namespace cannot be deleted until this is set to false.
     */
    enableDeleteProtection: boolean;
}

export interface GetNamespacePrivateConnectivity {
    /**
     * The AWS PrivateLink info. This will only be set for namespaces whose cloud provider is AWS.
     */
    awsPrivateLinkInfo: outputs.GetNamespacePrivateConnectivityAwsPrivateLinkInfo;
    /**
     * The id of the region where the private connectivity applies.
     */
    region: string;
}

export interface GetNamespacePrivateConnectivityAwsPrivateLinkInfo {
    /**
     * The list of principal arns that are allowed to access the namespace on the private link.
     */
    allowedPrincipalArns: string[];
    /**
     * The list of vpc endpoint service names that are associated with the namespace.
     */
    vpcEndpointServiceNames: string[];
}

export interface GetNamespacesNamespace {
    /**
     * The Base64-encoded CA cert in PEM format that clients use when authenticating with Temporal Cloud.
     */
    acceptedClientCa: string;
    /**
     * The currently active region for the namespace.
     */
    activeRegion: string;
    /**
     * If true, Temporal Cloud will use API key authentication for this namespace. If false, mutual TLS (mTLS) authentication will be used.
     */
    apiKeyAuth?: boolean;
    /**
     * A list of filters to apply to client certificates when initiating a connection Temporal Cloud. If present, connections will only be allowed from client certificates whose distinguished name properties match at least one of the filters.
     */
    certificateFilters: outputs.GetNamespacesNamespaceCertificateFilter[];
    /**
     * A codec server is used by the Temporal Cloud UI to decode payloads for all users interacting with this namespace, even if the workflow history itself is encrypted.
     */
    codecServer: outputs.GetNamespacesNamespaceCodecServer;
    /**
     * The IDs of the connectivity rules for this namespace.
     */
    connectivityRuleIds: string[];
    /**
     * The date and time when the namespace was created.
     */
    createdTime: string;
    /**
     * The custom search attributes to use for the namespace.
     */
    customSearchAttributes: {[key: string]: string};
    /**
     * The endpoints for the namespace.
     */
    endpoints: outputs.GetNamespacesNamespaceEndpoints;
    /**
     * The unique identifier of the namespace across all Temporal Cloud tenants.
     */
    id: string;
    /**
     * The date and time when the namespace was last modified. Will not be set if the namespace has never been modified.
     */
    lastModifiedTime: string;
    /**
     * The limits set on the namespace currently.
     */
    limits: outputs.GetNamespacesNamespaceLimits;
    /**
     * The name of the namespace.
     */
    name: string;
    /**
     * The lifecycle settings for the namespace.
     */
    namespaceLifecycle: outputs.GetNamespacesNamespaceNamespaceLifecycle;
    /**
     * The private connectivities for the namespace, if any.
     */
    privateConnectivities: outputs.GetNamespacesNamespacePrivateConnectivity[];
    /**
     * The list of regions that this namespace is available in. If more than one region is specified, this namespace is a Multi-region Namespace, which is currently unsupported by the Terraform provider.
     */
    regions: string[];
    /**
     * The number of days to retain workflow history. Any changes to the retention period will be applied to all new running workflows.
     */
    retentionDays: number;
    /**
     * The current state of the namespace.
     */
    state: string;
    /**
     * The tags for the namespace.
     */
    tags: {[key: string]: string};
}

export interface GetNamespacesNamespaceCertificateFilter {
    /**
     * The certificate's common name.
     */
    commonName: string;
    /**
     * The certificate's organization.
     */
    organization: string;
    /**
     * The certificate's organizational unit.
     */
    organizationalUnit: string;
    /**
     * The certificate's subject alternative name (or SAN).
     */
    subjectAlternativeName: string;
}

export interface GetNamespacesNamespaceCodecServer {
    /**
     * The endpoint of the codec server.
     */
    endpoint: string;
    /**
     * If true, Temporal Cloud will include cross-origin credentials in requests to the codec server.
     */
    includeCrossOriginCredentials: boolean;
    /**
     * If true, Temporal Cloud will pass the access token to the codec server upon each request.
     */
    passAccessToken: boolean;
}

export interface GetNamespacesNamespaceEndpoints {
    /**
     * The gRPC hostport address that the temporal workers, clients and tctl connect to.
     */
    grpcAddress: string;
    /**
     * The web UI address.
     */
    webAddress: string;
}

export interface GetNamespacesNamespaceLimits {
    /**
     * The number of actions per second (APS) that is currently allowed for the namespace. The namespace may be throttled if its APS exceeds the limit.
     */
    actionsPerSecondLimit: number;
}

export interface GetNamespacesNamespaceNamespaceLifecycle {
    /**
     * If true, delete protection is enabled for the namespace. This means that the namespace cannot be deleted until this is set to false.
     */
    enableDeleteProtection: boolean;
}

export interface GetNamespacesNamespacePrivateConnectivity {
    /**
     * The AWS PrivateLink info. This will only be set for namespaces whose cloud provider is AWS.
     */
    awsPrivateLinkInfo: outputs.GetNamespacesNamespacePrivateConnectivityAwsPrivateLinkInfo;
    /**
     * The id of the region where the private connectivity applies.
     */
    region: string;
}

export interface GetNamespacesNamespacePrivateConnectivityAwsPrivateLinkInfo {
    /**
     * The list of principal arns that are allowed to access the namespace on the private link.
     */
    allowedPrincipalArns: string[];
    /**
     * The list of vpc endpoint service names that are associated with the namespace.
     */
    vpcEndpointServiceNames: string[];
}

export interface GetNexusEndpointWorkerTarget {
    /**
     * The target cloud namespace to route requests to. Namespace is in same account as the endpoint.
     */
    namespaceId: string;
    /**
     * The task queue on the cloud namespace to route requests to.
     */
    taskQueue: string;
}

export interface GetNexusEndpointsNexusEndpoint {
    /**
     * Namespace Id(s) that are allowed to call this Endpoint.
     */
    allowedCallerNamespaces: string[];
    /**
     * The creation time of the Nexus Endpoint.
     */
    createdAt: string;
    /**
     * The description of the Nexus Endpoint.
     */
    description: string;
    /**
     * The unique identifier of the Nexus Endpoint.
     */
    id: string;
    /**
     * The name of the endpoint. Unique within an account and match `^[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9]$`
     */
    name: string;
    /**
     * The current state of the Nexus Endpoint.
     */
    state: string;
    /**
     * The last update time of the Nexus Endpoint.
     */
    updatedAt: string;
    /**
     * The target spec for routing nexus requests to a specific cloud namespace worker.
     */
    workerTarget: outputs.GetNexusEndpointsNexusEndpointWorkerTarget;
}

export interface GetNexusEndpointsNexusEndpointWorkerTarget {
    /**
     * The target cloud namespace to route requests to. Namespace is in same account as the endpoint.
     */
    namespaceId: string;
    /**
     * The task queue on the cloud namespace to route requests to.
     */
    taskQueue: string;
}

export interface GetRegionsRegion {
    /**
     * The name of the Cloud provider for this region, e.g. `aws`.
     */
    cloudProvider: string;
    /**
     * The name of the region within the Cloud provider, e.g. `us-east-1`.
     */
    cloudProviderRegion: string;
    /**
     * The unique identifier for the region, e.g. `aws-us-east-1`.
     */
    id: string;
    /**
     * The physical location of the region, e.g. "US East (N. Virginia)".
     */
    location: string;
}

export interface GetServiceAccountNamespaceAccess {
    /**
     * The namespace to assign permissions to.
     */
    namespaceId: string;
    /**
     * The permission to assign. Must be one of admin, write, or read (case-insensitive).
     */
    permission: string;
}

export interface GetServiceAccountNamespaceScopedAccess {
    /**
     * The namespace this service account is scoped to.
     */
    namespaceId: string;
    /**
     * The permission to assign. Must be one of admin, write, or read (case-insensitive).
     */
    permission: string;
}

export interface GetServiceAccountsServiceAccount {
    /**
     * The role on the account. Must be one of admin, developer, read, or metricsread (case-insensitive).
     */
    accountAccess: string;
    /**
     * The creation time of the Service Account.
     */
    createdAt: string;
    /**
     * The description of the Service Account.
     */
    description: string;
    /**
     * The unique identifier of the Service Account.
     */
    id: string;
    /**
     * The name associated with the service account.
     */
    name: string;
    /**
     * The set of namespace permissions for this service account, including each namespace and its role.
     */
    namespaceAccesses: outputs.GetServiceAccountsServiceAccountNamespaceAccess[];
    /**
     * The namespace-scoped access configuration for this service account.
     */
    namespaceScopedAccess: outputs.GetServiceAccountsServiceAccountNamespaceScopedAccess;
    /**
     * The current state of the Service Account.
     */
    state: string;
    /**
     * The last update time of the Service Account.
     */
    updatedAt: string;
}

export interface GetServiceAccountsServiceAccountNamespaceAccess {
    /**
     * The namespace to assign permissions to.
     */
    namespaceId: string;
    /**
     * The permission to assign. Must be one of admin, write, or read (case-insensitive).
     */
    permission: string;
}

export interface GetServiceAccountsServiceAccountNamespaceScopedAccess {
    /**
     * The namespace this service account is scoped to.
     */
    namespaceId: string;
    /**
     * The permission to assign. Must be one of admin, write, or read (case-insensitive).
     */
    permission: string;
}

export interface GetUserNamespaceAccess {
    /**
     * The namespace to assign permissions to.
     */
    namespaceId: string;
    /**
     * The permission to assign. Must be one of admin, write, or read (case-insensitive)
     */
    permission: string;
}

export interface GetUsersUser {
    /**
     * The role on the account. Must be one of admin, developer, or read (case-insensitive).
     */
    accountAccess: string;
    /**
     * The creation time of the User.
     */
    createdAt: string;
    /**
     * The email of the User.
     */
    email: string;
    /**
     * The unique identifier of the User.
     */
    id: string;
    /**
     * The set of namespace permissions for this user, including each namespace and its role.
     */
    namespaceAccesses: outputs.GetUsersUserNamespaceAccess[];
    /**
     * The current state of the User.
     */
    state: string;
    /**
     * The last update time of the User.
     */
    updatedAt: string;
}

export interface GetUsersUserNamespaceAccess {
    /**
     * The namespace to assign permissions to.
     */
    namespaceId: string;
    /**
     * The permission to assign. Must be one of admin, write, or read (case-insensitive)
     */
    permission: string;
}

export interface GroupAccessNamespaceAccess {
    /**
     * The namespace to assign permissions to.
     */
    namespaceId: string;
    /**
     * The permission to assign. Must be one of admin, write, or read (case-insensitive)
     */
    permission: string;
}

export interface GroupMembersTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: string;
}

export interface GroupTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: string;
}

export interface MetricsEndpointTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    update?: string;
}

export interface NamespaceCapacity {
    /**
     * The mode of the capacity configuration. Must be one of 'provisioned' or 'on_demand'.
     */
    mode?: string;
    /**
     * The value of the capacity configuration. Must be set when mode is 'provisioned'.
     */
    value?: number;
}

export interface NamespaceCertificateFilter {
    /**
     * The certificate's common name.
     */
    commonName?: string;
    /**
     * The certificate's organization.
     */
    organization?: string;
    /**
     * The certificate's organizational unit.
     */
    organizationalUnit?: string;
    /**
     * The certificate's subject alternative name (or SAN).
     */
    subjectAlternativeName?: string;
}

export interface NamespaceCodecServer {
    /**
     * The endpoint of the codec server. Must begin with "https".
     */
    endpoint: string;
    /**
     * If true, Temporal Cloud will include cross-origin credentials in requests to the codec server.
     */
    includeCrossOriginCredentials: boolean;
    /**
     * If true, Temporal Cloud will pass the access token to the codec server upon each request.
     */
    passAccessToken: boolean;
}

export interface NamespaceEndpoints {
    /**
     * The gRPC address for API key client connections (may be empty if API keys are disabled).
     */
    grpcAddress: string;
    /**
     * The gRPC address for mTLS client connections (may be empty if mTLS is disabled).
     */
    mtlsGrpcAddress: string;
    /**
     * The address in the Temporal Cloud Web UI for the namespace
     */
    webAddress: string;
}

export interface NamespaceExportSinkGcs {
    /**
     * The name of the destination GCS bucket where Temporal will send data.
     */
    bucketName: string;
    /**
     * The GCP project ID associated with the GCS bucket and service account. If not provided, the service*account*email must be provided.
     */
    gcpProjectId: string;
    /**
     * The region of the gcs bucket
     */
    region: string;
    /**
     * The service account email associated with the GCS bucket and service account. If not provided, the service*account*id and gcp*project*id must be provided.
     */
    serviceAccountEmail: string;
    /**
     * The customer service account ID that Temporal Cloud impersonates for writing records to the customer's GCS bucket. If not provided, the service*account*email must be provided.
     */
    serviceAccountId: string;
}

export interface NamespaceExportSinkS3 {
    /**
     * The AWS account ID associated with the S3 bucket and the assumed role.
     */
    awsAccountId: string;
    /**
     * The name of the destination S3 bucket where Temporal will send data.
     */
    bucketName: string;
    /**
     * The AWS Key Management Service (KMS) ARN used for encryption.
     */
    kmsArn?: string;
    /**
     * The region where the S3 bucket is located.
     */
    region: string;
    /**
     * The IAM role that Temporal Cloud assumes for writing records to the customer's S3 bucket.
     */
    roleName: string;
}

export interface NamespaceExportSinkTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: string;
}

export interface NamespaceNamespaceLifecycle {
    /**
     * If true, the namespace cannot be deleted. This is a safeguard against accidental deletion. To delete a namespace with this option enabled, you must first set it to false.
     */
    enableDeleteProtection: boolean;
}

export interface NamespaceTagsTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: string;
}

export interface NamespaceTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: string;
}

export interface NexusEndpointTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: string;
}

export interface NexusEndpointWorkerTarget {
    /**
     * The target cloud namespace to route requests to. Namespace must be in same account as the endpoint.
     */
    namespaceId: string;
    /**
     * The task queue on the cloud namespace to route requests to.
     */
    taskQueue: string;
}

export interface ServiceAccountNamespaceAccess {
    /**
     * The namespace to assign permissions to.
     */
    namespaceId: string;
    /**
     * The permission to assign. Must be one of admin, write, or read (case-insensitive)
     */
    permission: string;
}

export interface ServiceAccountNamespaceScopedAccess {
    /**
     * The namespace to scope this service account to. This field is immutable after creation.
     */
    namespaceId: string;
    /**
     * The permission to assign. Must be one of admin, write, or read (case-insensitive). This field is mutable.
     */
    permission: string;
}

export interface ServiceAccountTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: string;
}

export interface UserNamespaceAccess {
    /**
     * The namespace to assign permissions to.
     */
    namespaceId: string;
    /**
     * The permission to assign. Must be one of admin, write, or read (case-insensitive)
     */
    permission: string;
}

export interface UserTimeouts {
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
     */
    create?: string;
    /**
     * A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
     */
    delete?: string;
}

