// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provisions an account audit log sink.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as temporalcloud from "@pulumi/temporalcloud";
 *
 * // Example with Kinesis
 * const kinesisSink = new temporalcloud.AccountAuditLogSink("kinesis_sink", {
 *     sinkName: "my-kinesis-sink",
 *     enabled: true,
 *     kinesis: {
 *         roleName: "arn:aws:iam::123456789012:role/TemporalCloudKinesisRole",
 *         destinationUri: "arn:aws:kinesis:us-east-1:123456789012:stream/my-audit-stream",
 *         region: "us-east-1",
 *     },
 * });
 * // Example with PubSub
 * const pubsubSink = new temporalcloud.AccountAuditLogSink("pubsub_sink", {
 *     sinkName: "my-pubsub-sink",
 *     enabled: true,
 *     pubsub: {
 *         serviceAccountId: "my-service-account-id",
 *         topicName: "temporal-audit-logs",
 *         gcpProjectId: "my-gcp-project",
 *     },
 * });
 * ```
 */
export class AccountAuditLogSink extends pulumi.CustomResource {
    /**
     * Get an existing AccountAuditLogSink resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AccountAuditLogSinkState, opts?: pulumi.CustomResourceOptions): AccountAuditLogSink {
        return new AccountAuditLogSink(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'temporalcloud:index/accountAuditLogSink:AccountAuditLogSink';

    /**
     * Returns true if the given object is an instance of AccountAuditLogSink.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AccountAuditLogSink {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AccountAuditLogSink.__pulumiType;
    }

    /**
     * A flag indicating whether the audit log sink is enabled or not.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * The Kinesis configuration details when destinationType is Kinesis.
     */
    declare public readonly kinesis: pulumi.Output<outputs.AccountAuditLogSinkKinesis | undefined>;
    /**
     * The PubSub configuration details when destinationType is PubSub.
     */
    declare public readonly pubsub: pulumi.Output<outputs.AccountAuditLogSinkPubsub | undefined>;
    /**
     * The unique name of the audit log sink, it can't be changed once set.
     */
    declare public readonly sinkName: pulumi.Output<string>;
    declare public readonly timeouts: pulumi.Output<outputs.AccountAuditLogSinkTimeouts | undefined>;

    /**
     * Create a AccountAuditLogSink resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AccountAuditLogSinkArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AccountAuditLogSinkArgs | AccountAuditLogSinkState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AccountAuditLogSinkState | undefined;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["kinesis"] = state?.kinesis;
            resourceInputs["pubsub"] = state?.pubsub;
            resourceInputs["sinkName"] = state?.sinkName;
            resourceInputs["timeouts"] = state?.timeouts;
        } else {
            const args = argsOrState as AccountAuditLogSinkArgs | undefined;
            if (args?.sinkName === undefined && !opts.urn) {
                throw new Error("Missing required property 'sinkName'");
            }
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["kinesis"] = args?.kinesis;
            resourceInputs["pubsub"] = args?.pubsub;
            resourceInputs["sinkName"] = args?.sinkName;
            resourceInputs["timeouts"] = args?.timeouts;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(AccountAuditLogSink.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AccountAuditLogSink resources.
 */
export interface AccountAuditLogSinkState {
    /**
     * A flag indicating whether the audit log sink is enabled or not.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * The Kinesis configuration details when destinationType is Kinesis.
     */
    kinesis?: pulumi.Input<inputs.AccountAuditLogSinkKinesis | undefined>;
    /**
     * The PubSub configuration details when destinationType is PubSub.
     */
    pubsub?: pulumi.Input<inputs.AccountAuditLogSinkPubsub | undefined>;
    /**
     * The unique name of the audit log sink, it can't be changed once set.
     */
    sinkName?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.AccountAuditLogSinkTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a AccountAuditLogSink resource.
 */
export interface AccountAuditLogSinkArgs {
    /**
     * A flag indicating whether the audit log sink is enabled or not.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * The Kinesis configuration details when destinationType is Kinesis.
     */
    kinesis?: pulumi.Input<inputs.AccountAuditLogSinkKinesis | undefined>;
    /**
     * The PubSub configuration details when destinationType is PubSub.
     */
    pubsub?: pulumi.Input<inputs.AccountAuditLogSinkPubsub | undefined>;
    /**
     * The unique name of the audit log sink, it can't be changed once set.
     */
    sinkName: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.AccountAuditLogSinkTimeouts | undefined>;
}
