// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provisions a Temporal Cloud Connectivity Rule.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as temporalcloud from "@pulumi/temporalcloud";
 *
 * // Create Public Connectivity Rule
 * const publicRule = new temporalcloud.ConnectivityRule("public_rule", {connectivityType: "public"});
 * // Create Private Connectivity Rule for AWS
 * const privateAws = new temporalcloud.ConnectivityRule("private_aws", {
 *     connectivityType: "private",
 *     connectionId: "vpce-12345678",
 *     region: "aws-us-west-2",
 * });
 * // Create Private Connectivity Rule for GCP
 * const privateGcp = new temporalcloud.ConnectivityRule("private_gcp", {
 *     connectivityType: "private",
 *     connectionId: "vpce-12345678",
 *     region: "gcp-us-central1",
 *     gcpProjectId: "my-gcp-project-id",
 * });
 * // Attaching connectivity rules to a namespace
 * const ns_with_cr = new temporalcloud.Namespace("ns-with-cr", {
 *     name: "ns-with-cr",
 *     regions: ["aws-us-west-2"],
 *     apiKeyAuth: true,
 *     retentionDays: 14,
 *     connectivityRuleIds: [
 *         id,
 *         idPrivateAws,
 *     ],
 * });
 * ```
 */
export class ConnectivityRule extends pulumi.CustomResource {
    /**
     * Get an existing ConnectivityRule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConnectivityRuleState, opts?: pulumi.CustomResourceOptions): ConnectivityRule {
        return new ConnectivityRule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'temporalcloud:index/connectivityRule:ConnectivityRule';

    /**
     * Returns true if the given object is an instance of ConnectivityRule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ConnectivityRule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ConnectivityRule.__pulumiType;
    }

    /**
     * The connection ID of the private connection.
     */
    declare public readonly connectionId: pulumi.Output<string | undefined>;
    /**
     * The type of connectivity. Must be one of 'public' or 'private'.
     */
    declare public readonly connectivityType: pulumi.Output<string>;
    /**
     * The GCP project ID. Required when cloudProvider is 'gcp'.
     */
    declare public readonly gcpProjectId: pulumi.Output<string | undefined>;
    /**
     * The region of the connection. Example: 'aws-us-west-2'.
     */
    declare public readonly region: pulumi.Output<string | undefined>;
    declare public readonly timeouts: pulumi.Output<outputs.ConnectivityRuleTimeouts | undefined>;

    /**
     * Create a ConnectivityRule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ConnectivityRuleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConnectivityRuleArgs | ConnectivityRuleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConnectivityRuleState | undefined;
            resourceInputs["connectionId"] = state?.connectionId;
            resourceInputs["connectivityType"] = state?.connectivityType;
            resourceInputs["gcpProjectId"] = state?.gcpProjectId;
            resourceInputs["region"] = state?.region;
            resourceInputs["timeouts"] = state?.timeouts;
        } else {
            const args = argsOrState as ConnectivityRuleArgs | undefined;
            if (args?.connectivityType === undefined && !opts.urn) {
                throw new Error("Missing required property 'connectivityType'");
            }
            resourceInputs["connectionId"] = args?.connectionId;
            resourceInputs["connectivityType"] = args?.connectivityType;
            resourceInputs["gcpProjectId"] = args?.gcpProjectId;
            resourceInputs["region"] = args?.region;
            resourceInputs["timeouts"] = args?.timeouts;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ConnectivityRule.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ConnectivityRule resources.
 */
export interface ConnectivityRuleState {
    /**
     * The connection ID of the private connection.
     */
    connectionId?: pulumi.Input<string | undefined>;
    /**
     * The type of connectivity. Must be one of 'public' or 'private'.
     */
    connectivityType?: pulumi.Input<string | undefined>;
    /**
     * The GCP project ID. Required when cloudProvider is 'gcp'.
     */
    gcpProjectId?: pulumi.Input<string | undefined>;
    /**
     * The region of the connection. Example: 'aws-us-west-2'.
     */
    region?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.ConnectivityRuleTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a ConnectivityRule resource.
 */
export interface ConnectivityRuleArgs {
    /**
     * The connection ID of the private connection.
     */
    connectionId?: pulumi.Input<string | undefined>;
    /**
     * The type of connectivity. Must be one of 'public' or 'private'.
     */
    connectivityType: pulumi.Input<string>;
    /**
     * The GCP project ID. Required when cloudProvider is 'gcp'.
     */
    gcpProjectId?: pulumi.Input<string | undefined>;
    /**
     * The region of the connection. Example: 'aws-us-west-2'.
     */
    region?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.ConnectivityRuleTimeouts | undefined>;
}
