// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provisions a Temporal Cloud custom role.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as temporalcloud from "@pulumi/temporalcloud";
 *
 * const exampleCustomRole = new temporalcloud.CustomRole("example_custom_role", {
 *     name: "terraform-example-custom-role",
 *     description: "Example custom role created with Terraform.",
 *     permissions: [{
 *         actions: ["cloud.account.get"],
 *         resources: {
 *             resourceType: "accounts",
 *             resourceIds: [],
 *             allowAll: true,
 *         },
 *     }],
 * });
 * ```
 */
export class CustomRole extends pulumi.CustomResource {
    /**
     * Get an existing CustomRole resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CustomRoleState, opts?: pulumi.CustomResourceOptions): CustomRole {
        return new CustomRole(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'temporalcloud:index/customRole:CustomRole';

    /**
     * Returns true if the given object is an instance of CustomRole.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CustomRole {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CustomRole.__pulumiType;
    }

    /**
     * The description of the custom role.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * The name of the custom role.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The permissions assigned to the custom role.
     */
    declare public readonly permissions: pulumi.Output<outputs.CustomRolePermission[]>;
    /**
     * The current state of the custom role.
     */
    declare public /*out*/ readonly state: pulumi.Output<string>;
    declare public readonly timeouts: pulumi.Output<outputs.CustomRoleTimeouts | undefined>;

    /**
     * Create a CustomRole resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CustomRoleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CustomRoleArgs | CustomRoleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CustomRoleState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["name"] = state?.name;
            resourceInputs["permissions"] = state?.permissions;
            resourceInputs["state"] = state?.state;
            resourceInputs["timeouts"] = state?.timeouts;
        } else {
            const args = argsOrState as CustomRoleArgs | undefined;
            if (args?.permissions === undefined && !opts.urn) {
                throw new Error("Missing required property 'permissions'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["name"] = args?.name;
            resourceInputs["permissions"] = args?.permissions;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["state"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CustomRole.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CustomRole resources.
 */
export interface CustomRoleState {
    /**
     * The description of the custom role.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The name of the custom role.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The permissions assigned to the custom role.
     */
    permissions?: pulumi.Input<pulumi.Input<inputs.CustomRolePermission>[] | undefined>;
    /**
     * The current state of the custom role.
     */
    state?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.CustomRoleTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a CustomRole resource.
 */
export interface CustomRoleArgs {
    /**
     * The description of the custom role.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The name of the custom role.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The permissions assigned to the custom role.
     */
    permissions: pulumi.Input<pulumi.Input<inputs.CustomRolePermission>[]>;
    timeouts?: pulumi.Input<inputs.CustomRoleTimeouts | undefined>;
}
