// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Fetches details about an account audit log sink.
 */
export function getAccountAuditLogSink(args: GetAccountAuditLogSinkArgs, opts?: pulumi.InvokeOptions): Promise<GetAccountAuditLogSinkResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("temporalcloud:index/getAccountAuditLogSink:getAccountAuditLogSink", {
        "sinkName": args.sinkName,
    }, opts);
}

/**
 * A collection of arguments for invoking getAccountAuditLogSink.
 */
export interface GetAccountAuditLogSinkArgs {
    /**
     * The unique name of the audit log sink.
     */
    sinkName: string;
}

/**
 * A collection of values returned by getAccountAuditLogSink.
 */
export interface GetAccountAuditLogSinkResult {
    /**
     * A flag indicating whether the audit log sink is enabled or not.
     */
    readonly enabled: boolean;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * The Kinesis configuration details when destinationType is Kinesis.
     */
    readonly kinesis: outputs.GetAccountAuditLogSinkKinesis;
    /**
     * The PubSub configuration details when destinationType is PubSub.
     */
    readonly pubsub: outputs.GetAccountAuditLogSinkPubsub;
    /**
     * The unique name of the audit log sink.
     */
    readonly sinkName: string;
    /**
     * The current state of the audit log sink.
     */
    readonly state: string;
}
/**
 * Fetches details about an account audit log sink.
 */
export function getAccountAuditLogSinkOutput(args: GetAccountAuditLogSinkOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetAccountAuditLogSinkResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("temporalcloud:index/getAccountAuditLogSink:getAccountAuditLogSink", {
        "sinkName": args.sinkName,
    }, opts);
}

/**
 * A collection of arguments for invoking getAccountAuditLogSink.
 */
export interface GetAccountAuditLogSinkOutputArgs {
    /**
     * The unique name of the audit log sink.
     */
    sinkName: pulumi.Input<string>;
}
