// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Fetches details about a connectivity rule.
 */
export function getConnectivityRule(args: GetConnectivityRuleArgs, opts?: pulumi.InvokeOptions): Promise<GetConnectivityRuleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("temporalcloud:index/getConnectivityRule:getConnectivityRule", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getConnectivityRule.
 */
export interface GetConnectivityRuleArgs {
    /**
     * The unique identifier of the connectivity rule across all Temporal Cloud tenants.
     */
    id: string;
}

/**
 * A collection of values returned by getConnectivityRule.
 */
export interface GetConnectivityRuleResult {
    /**
     * The ARM resource ID of the customer's Azure Private Endpoint for the connectivity rule.
     */
    readonly azurePeResourceId: string;
    /**
     * The ID of the connection to the connectivity rule.
     */
    readonly connectionId: string;
    /**
     * The type of connectivity.
     */
    readonly connectivityType: string;
    /**
     * The time the connectivity rule was created.
     */
    readonly createdAt: string;
    /**
     * If true, namespaces attached to this public connectivity rule are reachable via a predictable set of public IPs. Only set for public connectivity rules.
     */
    readonly enableStableIps: boolean;
    /**
     * The GCP project ID of the connectivity rule.
     */
    readonly gcpProjectId: string;
    /**
     * The unique identifier of the connectivity rule across all Temporal Cloud tenants.
     */
    readonly id: string;
    /**
     * The region of the connectivity rule.
     */
    readonly region: string;
    /**
     * The current state of the connectivity rule.
     */
    readonly state: string;
}
/**
 * Fetches details about a connectivity rule.
 */
export function getConnectivityRuleOutput(args: GetConnectivityRuleOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetConnectivityRuleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("temporalcloud:index/getConnectivityRule:getConnectivityRule", {
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getConnectivityRule.
 */
export interface GetConnectivityRuleOutputArgs {
    /**
     * The unique identifier of the connectivity rule across all Temporal Cloud tenants.
     */
    id: pulumi.Input<string>;
}
