// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Fetches details about all Nexus Endpoints.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as temporalcloud from "@pulumi/temporalcloud";
 *
 * const myNexusEndpoints = temporalcloud.getNexusEndpoints({});
 * export const nexusEndpoints = myNexusEndpoints.then(myNexusEndpoints => myNexusEndpoints.nexusEndpoints);
 * ```
 */
export function getNexusEndpoints(opts?: pulumi.InvokeOptions): Promise<GetNexusEndpointsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("temporalcloud:index/getNexusEndpoints:getNexusEndpoints", {
    }, opts);
}

/**
 * A collection of values returned by getNexusEndpoints.
 */
export interface GetNexusEndpointsResult {
    /**
     * The unique identifier of the Nexus Endpoints data source.
     */
    readonly id: string;
    /**
     * The list of Nexus Endpoints.
     */
    readonly nexusEndpoints: outputs.GetNexusEndpointsNexusEndpoint[];
}
/**
 * Fetches details about all Nexus Endpoints.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as temporalcloud from "@pulumi/temporalcloud";
 *
 * const myNexusEndpoints = temporalcloud.getNexusEndpoints({});
 * export const nexusEndpoints = myNexusEndpoints.then(myNexusEndpoints => myNexusEndpoints.nexusEndpoints);
 * ```
 */
export function getNexusEndpointsOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetNexusEndpointsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("temporalcloud:index/getNexusEndpoints:getNexusEndpoints", {
    }, opts);
}
