// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Fetches details about a Nexus Endpoint.
 */
export function getNexusEndpoint(args: GetNexusEndpointArgs, opts?: pulumi.InvokeOptions): Promise<GetNexusEndpointResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("temporalcloud:index/getNexusEndpoint:getNexusEndpoint", {
        "description": args.description,
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getNexusEndpoint.
 */
export interface GetNexusEndpointArgs {
    /**
     * The description of the Nexus Endpoint.
     */
    description?: string;
    /**
     * The unique identifier of the Nexus Endpoint.
     */
    id: string;
}

/**
 * A collection of values returned by getNexusEndpoint.
 */
export interface GetNexusEndpointResult {
    /**
     * Namespace Id(s) that are allowed to call this Endpoint.
     */
    readonly allowedCallerNamespaces: string[];
    /**
     * The creation time of the Nexus Endpoint.
     */
    readonly createdAt: string;
    /**
     * The description of the Nexus Endpoint.
     */
    readonly description: string;
    /**
     * The unique identifier of the Nexus Endpoint.
     */
    readonly id: string;
    /**
     * The name of the endpoint. Unique within an account and match `^[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9]$`
     */
    readonly name: string;
    /**
     * The current state of the Nexus Endpoint.
     */
    readonly state: string;
    /**
     * The last update time of the Nexus Endpoint.
     */
    readonly updatedAt: string;
    /**
     * The target spec for routing nexus requests to a specific cloud namespace worker.
     */
    readonly workerTarget: outputs.GetNexusEndpointWorkerTarget;
}
/**
 * Fetches details about a Nexus Endpoint.
 */
export function getNexusEndpointOutput(args: GetNexusEndpointOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetNexusEndpointResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("temporalcloud:index/getNexusEndpoint:getNexusEndpoint", {
        "description": args.description,
        "id": args.id,
    }, opts);
}

/**
 * A collection of arguments for invoking getNexusEndpoint.
 */
export interface GetNexusEndpointOutputArgs {
    /**
     * The description of the Nexus Endpoint.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The unique identifier of the Nexus Endpoint.
     */
    id: pulumi.Input<string>;
}
