// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Fetches details about a Namespace.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as temporalcloud from "@pulumi/temporalcloud";
 *
 * const myNamespace = temporalcloud.getNamespace({
 *     id: namespaceTemporalcloudNamespace,
 * });
 * export const namespace = myNamespaceTemporalcloudNamespaces;
 * ```
 */
export function getNamespace(args: GetNamespaceArgs, opts?: pulumi.InvokeOptions): Promise<GetNamespaceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("temporalcloud:index/getNamespace:getNamespace", {
        "apiKeyAuth": args.apiKeyAuth,
        "certificateFilters": args.certificateFilters,
        "codecServer": args.codecServer,
        "connectivityRuleIds": args.connectivityRuleIds,
        "customSearchAttributes": args.customSearchAttributes,
        "id": args.id,
        "lastModifiedTime": args.lastModifiedTime,
        "privateConnectivities": args.privateConnectivities,
        "tags": args.tags,
    }, opts);
}

/**
 * A collection of arguments for invoking getNamespace.
 */
export interface GetNamespaceArgs {
    /**
     * If true, Temporal Cloud will use API key authentication for this namespace. If false, mutual TLS (mTLS) authentication will be used.
     */
    apiKeyAuth?: boolean;
    /**
     * A list of filters to apply to client certificates when initiating a connection Temporal Cloud. If present, connections will only be allowed from client certificates whose distinguished name properties match at least one of the filters.
     */
    certificateFilters?: inputs.GetNamespaceCertificateFilter[];
    /**
     * A codec server is used by the Temporal Cloud UI to decode payloads for all users interacting with this namespace, even if the workflow history itself is encrypted.
     */
    codecServer?: inputs.GetNamespaceCodecServer;
    /**
     * The IDs of the connectivity rules for this namespace.
     */
    connectivityRuleIds?: string[];
    /**
     * The custom search attributes to use for the namespace.
     */
    customSearchAttributes?: {[key: string]: string};
    /**
     * The unique identifier of the namespace across all Temporal Cloud tenants.
     */
    id: string;
    /**
     * The date and time when the namespace was last modified. Will not be set if the namespace has never been modified.
     */
    lastModifiedTime?: string;
    /**
     * The private connectivities for the namespace, if any.
     */
    privateConnectivities?: inputs.GetNamespacePrivateConnectivity[];
    /**
     * The tags for the namespace.
     */
    tags?: {[key: string]: string};
}

/**
 * A collection of values returned by getNamespace.
 */
export interface GetNamespaceResult {
    /**
     * The Base64-encoded CA cert in PEM format that clients use when authenticating with Temporal Cloud.
     */
    readonly acceptedClientCa: string;
    /**
     * The currently active region for the namespace.
     */
    readonly activeRegion: string;
    /**
     * If true, Temporal Cloud will use API key authentication for this namespace. If false, mutual TLS (mTLS) authentication will be used.
     */
    readonly apiKeyAuth?: boolean;
    /**
     * A list of filters to apply to client certificates when initiating a connection Temporal Cloud. If present, connections will only be allowed from client certificates whose distinguished name properties match at least one of the filters.
     */
    readonly certificateFilters: outputs.GetNamespaceCertificateFilter[];
    /**
     * A codec server is used by the Temporal Cloud UI to decode payloads for all users interacting with this namespace, even if the workflow history itself is encrypted.
     */
    readonly codecServer: outputs.GetNamespaceCodecServer;
    /**
     * The IDs of the connectivity rules for this namespace.
     */
    readonly connectivityRuleIds: string[];
    /**
     * The date and time when the namespace was created.
     */
    readonly createdTime: string;
    /**
     * The custom search attributes to use for the namespace.
     */
    readonly customSearchAttributes: {[key: string]: string};
    /**
     * The endpoints for the namespace.
     */
    readonly endpoints: outputs.GetNamespaceEndpoints;
    /**
     * The unique identifier of the namespace across all Temporal Cloud tenants.
     */
    readonly id: string;
    /**
     * The date and time when the namespace was last modified. Will not be set if the namespace has never been modified.
     */
    readonly lastModifiedTime: string;
    /**
     * The limits set on the namespace currently.
     */
    readonly limits: outputs.GetNamespaceLimits;
    /**
     * The name of the namespace.
     */
    readonly name: string;
    /**
     * The lifecycle settings for the namespace.
     */
    readonly namespaceLifecycle: outputs.GetNamespaceNamespaceLifecycle;
    /**
     * The private connectivities for the namespace, if any.
     */
    readonly privateConnectivities: outputs.GetNamespacePrivateConnectivity[];
    /**
     * The list of regions that this namespace is available in. If more than one region is specified, this namespace is a Multi-region Namespace, which is currently unsupported by the Terraform provider.
     */
    readonly regions: string[];
    /**
     * The number of days to retain workflow history. Any changes to the retention period will be applied to all new running workflows.
     */
    readonly retentionDays: number;
    /**
     * The current state of the namespace.
     */
    readonly state: string;
    /**
     * The tags for the namespace.
     */
    readonly tags: {[key: string]: string};
}
/**
 * Fetches details about a Namespace.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as temporalcloud from "@pulumi/temporalcloud";
 *
 * const myNamespace = temporalcloud.getNamespace({
 *     id: namespaceTemporalcloudNamespace,
 * });
 * export const namespace = myNamespaceTemporalcloudNamespaces;
 * ```
 */
export function getNamespaceOutput(args: GetNamespaceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetNamespaceResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("temporalcloud:index/getNamespace:getNamespace", {
        "apiKeyAuth": args.apiKeyAuth,
        "certificateFilters": args.certificateFilters,
        "codecServer": args.codecServer,
        "connectivityRuleIds": args.connectivityRuleIds,
        "customSearchAttributes": args.customSearchAttributes,
        "id": args.id,
        "lastModifiedTime": args.lastModifiedTime,
        "privateConnectivities": args.privateConnectivities,
        "tags": args.tags,
    }, opts);
}

/**
 * A collection of arguments for invoking getNamespace.
 */
export interface GetNamespaceOutputArgs {
    /**
     * If true, Temporal Cloud will use API key authentication for this namespace. If false, mutual TLS (mTLS) authentication will be used.
     */
    apiKeyAuth?: pulumi.Input<boolean | undefined>;
    /**
     * A list of filters to apply to client certificates when initiating a connection Temporal Cloud. If present, connections will only be allowed from client certificates whose distinguished name properties match at least one of the filters.
     */
    certificateFilters?: pulumi.Input<pulumi.Input<inputs.GetNamespaceCertificateFilterArgs>[] | undefined>;
    /**
     * A codec server is used by the Temporal Cloud UI to decode payloads for all users interacting with this namespace, even if the workflow history itself is encrypted.
     */
    codecServer?: pulumi.Input<inputs.GetNamespaceCodecServerArgs | undefined>;
    /**
     * The IDs of the connectivity rules for this namespace.
     */
    connectivityRuleIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The custom search attributes to use for the namespace.
     */
    customSearchAttributes?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * The unique identifier of the namespace across all Temporal Cloud tenants.
     */
    id: pulumi.Input<string>;
    /**
     * The date and time when the namespace was last modified. Will not be set if the namespace has never been modified.
     */
    lastModifiedTime?: pulumi.Input<string | undefined>;
    /**
     * The private connectivities for the namespace, if any.
     */
    privateConnectivities?: pulumi.Input<pulumi.Input<inputs.GetNamespacePrivateConnectivityArgs>[] | undefined>;
    /**
     * The tags for the namespace.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
}
