// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Fetches details about a SCIM group.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as temporalcloud from "@pulumi/temporalcloud";
 *
 * const myScimGroup = new temporalcloud.index.ScimGroup("my_scim_group", {idpId: "usually-group-name"});
 * export const scimGroup = myScimGroupTemporalcloudScimGroup;
 * ```
 */
export function getScimGroup(args: GetScimGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetScimGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("temporalcloud:index/getScimGroup:getScimGroup", {
        "idpId": args.idpId,
    }, opts);
}

/**
 * A collection of arguments for invoking getScimGroup.
 */
export interface GetScimGroupArgs {
    /**
     * The IDP ID of the SCIM group.
     */
    idpId: string;
}

/**
 * A collection of values returned by getScimGroup.
 */
export interface GetScimGroupResult {
    /**
     * The ID of the SCIM group.
     */
    readonly id: string;
    /**
     * The IDP ID of the SCIM group.
     */
    readonly idpId: string;
    /**
     * The name of the SCIM group.
     */
    readonly name: string;
}
/**
 * Fetches details about a SCIM group.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as temporalcloud from "@pulumi/temporalcloud";
 *
 * const myScimGroup = new temporalcloud.index.ScimGroup("my_scim_group", {idpId: "usually-group-name"});
 * export const scimGroup = myScimGroupTemporalcloudScimGroup;
 * ```
 */
export function getScimGroupOutput(args: GetScimGroupOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetScimGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("temporalcloud:index/getScimGroup:getScimGroup", {
        "idpId": args.idpId,
    }, opts);
}

/**
 * A collection of arguments for invoking getScimGroup.
 */
export interface GetScimGroupOutputArgs {
    /**
     * The IDP ID of the SCIM group.
     */
    idpId: pulumi.Input<string>;
}
