// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Fetches details about a Service Account.
 */
export function getServiceAccount(args: GetServiceAccountArgs, opts?: pulumi.InvokeOptions): Promise<GetServiceAccountResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("temporalcloud:index/getServiceAccount:getServiceAccount", {
        "id": args.id,
        "namespaceAccesses": args.namespaceAccesses,
    }, opts);
}

/**
 * A collection of arguments for invoking getServiceAccount.
 */
export interface GetServiceAccountArgs {
    /**
     * The unique identifier of the Service Account.
     */
    id: string;
    /**
     * The set of namespace permissions for this service account, including each namespace and its role.
     */
    namespaceAccesses?: inputs.GetServiceAccountNamespaceAccess[];
}

/**
 * A collection of values returned by getServiceAccount.
 */
export interface GetServiceAccountResult {
    /**
     * The role on the account. Must be one of admin, developer, read, or metricsread (case-insensitive).
     */
    readonly accountAccess: string;
    /**
     * The creation time of the Service Account.
     */
    readonly createdAt: string;
    /**
     * The description of the Service Account.
     */
    readonly description: string;
    /**
     * The unique identifier of the Service Account.
     */
    readonly id: string;
    /**
     * The name associated with the service account.
     */
    readonly name: string;
    /**
     * The set of namespace permissions for this service account, including each namespace and its role.
     */
    readonly namespaceAccesses: outputs.GetServiceAccountNamespaceAccess[];
    /**
     * The namespace-scoped access configuration for this service account.
     */
    readonly namespaceScopedAccess: outputs.GetServiceAccountNamespaceScopedAccess;
    /**
     * The current state of the Service Account.
     */
    readonly state: string;
    /**
     * The last update time of the Service Account.
     */
    readonly updatedAt: string;
}
/**
 * Fetches details about a Service Account.
 */
export function getServiceAccountOutput(args: GetServiceAccountOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetServiceAccountResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("temporalcloud:index/getServiceAccount:getServiceAccount", {
        "id": args.id,
        "namespaceAccesses": args.namespaceAccesses,
    }, opts);
}

/**
 * A collection of arguments for invoking getServiceAccount.
 */
export interface GetServiceAccountOutputArgs {
    /**
     * The unique identifier of the Service Account.
     */
    id: pulumi.Input<string>;
    /**
     * The set of namespace permissions for this service account, including each namespace and its role.
     */
    namespaceAccesses?: pulumi.Input<pulumi.Input<inputs.GetServiceAccountNamespaceAccessArgs>[] | undefined>;
}
