// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Fetches details about a User.
 */
export function getUser(args: GetUserArgs, opts?: pulumi.InvokeOptions): Promise<GetUserResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("temporalcloud:index/getUser:getUser", {
        "id": args.id,
        "namespaceAccesses": args.namespaceAccesses,
    }, opts);
}

/**
 * A collection of arguments for invoking getUser.
 */
export interface GetUserArgs {
    /**
     * The unique identifier of the User.
     */
    id: string;
    /**
     * The set of namespace permissions for this user, including each namespace and its role.
     */
    namespaceAccesses?: inputs.GetUserNamespaceAccess[];
}

/**
 * A collection of values returned by getUser.
 */
export interface GetUserResult {
    /**
     * The role on the account. Must be one of admin, developer, or read (case-insensitive).
     */
    readonly accountAccess: string;
    /**
     * The creation time of the User.
     */
    readonly createdAt: string;
    /**
     * The email of the User.
     */
    readonly email: string;
    /**
     * The unique identifier of the User.
     */
    readonly id: string;
    /**
     * The set of namespace permissions for this user, including each namespace and its role.
     */
    readonly namespaceAccesses: outputs.GetUserNamespaceAccess[];
    /**
     * The current state of the User.
     */
    readonly state: string;
    /**
     * The last update time of the User.
     */
    readonly updatedAt: string;
}
/**
 * Fetches details about a User.
 */
export function getUserOutput(args: GetUserOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetUserResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("temporalcloud:index/getUser:getUser", {
        "id": args.id,
        "namespaceAccesses": args.namespaceAccesses,
    }, opts);
}

/**
 * A collection of arguments for invoking getUser.
 */
export interface GetUserOutputArgs {
    /**
     * The unique identifier of the User.
     */
    id: pulumi.Input<string>;
    /**
     * The set of namespace permissions for this user, including each namespace and its role.
     */
    namespaceAccesses?: pulumi.Input<pulumi.Input<inputs.GetUserNamespaceAccessArgs>[] | undefined>;
}
