// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provisions a Temporal Cloud User Group.
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * Groups can be imported to incorporate existing Groups into your Terraform pipeline.
 * To import a Group, you need
 * - a resource configuration in your Terraform configuration file/module to accept the imported Group. In the example below, the placeholder is "temporalcloud.Group" "group"
 * - the Group's ID, which is found using the Temporal Cloud CLI tcld g l. In the example below, this is 72360058153949edb2f1d47019c1e85f
 *
 * ```sh
 * $ pulumi import temporalcloud:index/group:Group group 72360058153949edb2f1d47019c1e85f
 * ```
 */
export class Group extends pulumi.CustomResource {
    /**
     * Get an existing Group resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GroupState, opts?: pulumi.CustomResourceOptions): Group {
        return new Group(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'temporalcloud:index/group:Group';

    /**
     * Returns true if the given object is an instance of Group.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Group {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Group.__pulumiType;
    }

    /**
     * The name of the group
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The current state of the group.
     */
    declare public /*out*/ readonly state: pulumi.Output<string>;
    declare public readonly timeouts: pulumi.Output<outputs.GroupTimeouts | undefined>;

    /**
     * Create a Group resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: GroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GroupArgs | GroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GroupState | undefined;
            resourceInputs["name"] = state?.name;
            resourceInputs["state"] = state?.state;
            resourceInputs["timeouts"] = state?.timeouts;
        } else {
            const args = argsOrState as GroupArgs | undefined;
            resourceInputs["name"] = args?.name;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["state"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Group.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Group resources.
 */
export interface GroupState {
    /**
     * The name of the group
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The current state of the group.
     */
    state?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.GroupTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a Group resource.
 */
export interface GroupArgs {
    /**
     * The name of the group
     */
    name?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.GroupTimeouts | undefined>;
}
