// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provisions Temporal Cloud group access.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as temporalcloud from "@pulumi/temporalcloud";
 *
 * const myScimGroup = temporalcloud.getScimGroup({
 *     idpId: "usually-group-name",
 * });
 * const test = new temporalcloud.Namespace("test", {
 *     name: "my-namespace",
 *     regions: ["aws-us-east-1"],
 *     apiKeyAuth: true,
 *     retentionDays: 7,
 * });
 * const myGroupAccess = new temporalcloud.GroupAccess("my_group_access", {
 *     groupAccessId: myScimGroupTemporalcloudScimGroup.id,
 *     accountAccess: "read",
 *     namespaceAccesses: [{
 *         namespaceId: test.id,
 *         permission: "write",
 *     }],
 * });
 * ```
 */
export class GroupAccess extends pulumi.CustomResource {
    /**
     * Get an existing GroupAccess resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GroupAccessState, opts?: pulumi.CustomResourceOptions): GroupAccess {
        return new GroupAccess(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'temporalcloud:index/groupAccess:GroupAccess';

    /**
     * Returns true if the given object is an instance of GroupAccess.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GroupAccess {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GroupAccess.__pulumiType;
    }

    /**
     * The role on the account. Must be one of owner, admin, developer, none, or read (case-insensitive). owner is only valid for import and cannot be created, updated or deleted without Temporal support. none is only valid for users managed via SCIM that derive their roles from group memberships or for group access resources.
     */
    declare public readonly accountAccess: pulumi.Output<string>;
    /**
     * The unique identifier of the group access across all Temporal Cloud tenants.
     */
    declare public readonly groupAccessId: pulumi.Output<string>;
    /**
     * The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Users with account*access roles of owner or admin cannot be assigned explicit permissions to namespaces. They implicitly receive access to all Namespaces.
     */
    declare public readonly namespaceAccesses: pulumi.Output<outputs.GroupAccessNamespaceAccess[] | undefined>;

    /**
     * Create a GroupAccess resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GroupAccessArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GroupAccessArgs | GroupAccessState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GroupAccessState | undefined;
            resourceInputs["accountAccess"] = state?.accountAccess;
            resourceInputs["groupAccessId"] = state?.groupAccessId;
            resourceInputs["namespaceAccesses"] = state?.namespaceAccesses;
        } else {
            const args = argsOrState as GroupAccessArgs | undefined;
            if (args?.accountAccess === undefined && !opts.urn) {
                throw new Error("Missing required property 'accountAccess'");
            }
            if (args?.groupAccessId === undefined && !opts.urn) {
                throw new Error("Missing required property 'groupAccessId'");
            }
            resourceInputs["accountAccess"] = args?.accountAccess;
            resourceInputs["groupAccessId"] = args?.groupAccessId;
            resourceInputs["namespaceAccesses"] = args?.namespaceAccesses;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GroupAccess.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GroupAccess resources.
 */
export interface GroupAccessState {
    /**
     * The role on the account. Must be one of owner, admin, developer, none, or read (case-insensitive). owner is only valid for import and cannot be created, updated or deleted without Temporal support. none is only valid for users managed via SCIM that derive their roles from group memberships or for group access resources.
     */
    accountAccess?: pulumi.Input<string | undefined>;
    /**
     * The unique identifier of the group access across all Temporal Cloud tenants.
     */
    groupAccessId?: pulumi.Input<string | undefined>;
    /**
     * The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Users with account*access roles of owner or admin cannot be assigned explicit permissions to namespaces. They implicitly receive access to all Namespaces.
     */
    namespaceAccesses?: pulumi.Input<pulumi.Input<inputs.GroupAccessNamespaceAccess>[] | undefined>;
}

/**
 * The set of arguments for constructing a GroupAccess resource.
 */
export interface GroupAccessArgs {
    /**
     * The role on the account. Must be one of owner, admin, developer, none, or read (case-insensitive). owner is only valid for import and cannot be created, updated or deleted without Temporal support. none is only valid for users managed via SCIM that derive their roles from group memberships or for group access resources.
     */
    accountAccess: pulumi.Input<string>;
    /**
     * The unique identifier of the group access across all Temporal Cloud tenants.
     */
    groupAccessId: pulumi.Input<string>;
    /**
     * The set of namespace accesses. Empty sets are not allowed, omit the attribute instead. Users with account*access roles of owner or admin cannot be assigned explicit permissions to namespaces. They implicitly receive access to all Namespaces.
     */
    namespaceAccesses?: pulumi.Input<pulumi.Input<inputs.GroupAccessNamespaceAccess>[] | undefined>;
}
