// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Sets Group Membership for the provided Group ID. Only use one per group.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as temporalcloud from "@pulumi/temporalcloud";
 *
 * const adminGroup = new temporalcloud.Group("admin_group", {name: "admins"});
 * const reader = new temporalcloud.User("reader", {
 *     email: "reader@yourdomain.com",
 *     accountAccess: "reader",
 * });
 * const adminGroupAccess = new temporalcloud.GroupAccess("admin_group_access", {
 *     groupId: adminGroup.id,
 *     accountAccess: "admin",
 * });
 * const adminGroupMembers = new temporalcloud.GroupMembers("admin_group_members", {
 *     groupId: adminGroup.id,
 *     users: [reader.id],
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * Group Members can be imported to incorporate existing Group Memberships into your Terraform pipeline.
 * To import Group Members, you need
 * - a resource configuration in your Terraform configuration file/module to accept the imported Group Members. In the example below, the placeholder is "temporalcloud.GroupMembers" "group"
 * - the Group's ID, which is found using the Temporal Cloud CLI tcld g l. In the example below, this is 72360058153949edb2f1d47019c1e85f
 *
 * ```sh
 * $ pulumi import temporalcloud:index/groupMembers:GroupMembers group 72360058153949edb2f1d47019c1e85f
 * ```
 */
export class GroupMembers extends pulumi.CustomResource {
    /**
     * Get an existing GroupMembers resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GroupMembersState, opts?: pulumi.CustomResourceOptions): GroupMembers {
        return new GroupMembers(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'temporalcloud:index/groupMembers:GroupMembers';

    /**
     * Returns true if the given object is an instance of GroupMembers.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GroupMembers {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GroupMembers.__pulumiType;
    }

    /**
     * The Group ID to set the members for.
     */
    declare public readonly groupId: pulumi.Output<string>;
    declare public readonly timeouts: pulumi.Output<outputs.GroupMembersTimeouts | undefined>;
    /**
     * The users to add to the group.
     */
    declare public readonly users: pulumi.Output<string[]>;

    /**
     * Create a GroupMembers resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GroupMembersArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GroupMembersArgs | GroupMembersState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GroupMembersState | undefined;
            resourceInputs["groupId"] = state?.groupId;
            resourceInputs["timeouts"] = state?.timeouts;
            resourceInputs["users"] = state?.users;
        } else {
            const args = argsOrState as GroupMembersArgs | undefined;
            if (args?.groupId === undefined && !opts.urn) {
                throw new Error("Missing required property 'groupId'");
            }
            if (args?.users === undefined && !opts.urn) {
                throw new Error("Missing required property 'users'");
            }
            resourceInputs["groupId"] = args?.groupId;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["users"] = args?.users;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GroupMembers.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering GroupMembers resources.
 */
export interface GroupMembersState {
    /**
     * The Group ID to set the members for.
     */
    groupId?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.GroupMembersTimeouts | undefined>;
    /**
     * The users to add to the group.
     */
    users?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * The set of arguments for constructing a GroupMembers resource.
 */
export interface GroupMembersArgs {
    /**
     * The Group ID to set the members for.
     */
    groupId: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.GroupMembersTimeouts | undefined>;
    /**
     * The users to add to the group.
     */
    users: pulumi.Input<pulumi.Input<string>[]>;
}
