// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Create a [search attribute](https://docs.temporal.io/visibility#search-attribute) in a Temporal Cloud namespace. Note the limits on [quantity](https://docs.temporal.io/cloud/limits#number-of-custom-search-attributes) and [naming](https://docs.temporal.io/cloud/limits#custom-search-attribute-names).
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * Search Attributes can be imported to incorporate existing Namespace Search Attributes into your Terraform pipeline.
 * To import a Search Attribute, you need
 * - a resource configuration in your Terraform configuration file/module to accept the imported Search Attribute. In the example below, the placeholder is "temporalcloud.NamespaceSearchAttribute" "saimport"
 * - the Namespace ID, which includes the Namespace Name and Account ID available at the top of the Namespace's page in the Temporal Cloud UI. In the example below, this is namespaceid.acctid
 * - the name of the Search Attribute, which is available in the Search Attribute configuration of Namespace's page in the Temporal Cloud UI. In the example below, this is searchAttr
 *
 * ```sh
 * $ pulumi import temporalcloud:index/namespaceSearchAttribute:NamespaceSearchAttribute saimport namespaceid.acctid/searchAttr
 * ```
 */
export class NamespaceSearchAttribute extends pulumi.CustomResource {
    /**
     * Get an existing NamespaceSearchAttribute resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NamespaceSearchAttributeState, opts?: pulumi.CustomResourceOptions): NamespaceSearchAttribute {
        return new NamespaceSearchAttribute(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'temporalcloud:index/namespaceSearchAttribute:NamespaceSearchAttribute';

    /**
     * Returns true if the given object is an instance of NamespaceSearchAttribute.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NamespaceSearchAttribute {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NamespaceSearchAttribute.__pulumiType;
    }

    /**
     * The name of the search attribute.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The ID of the namespace to which this search attribute belongs.
     */
    declare public readonly namespaceId: pulumi.Output<string>;
    /**
     * The type of the search attribute. Must be one of `bool`, `datetime`, `double`, `int`, `keyword`, `keywordList` or `text`. (case-insensitive)
     */
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a NamespaceSearchAttribute resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NamespaceSearchAttributeArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NamespaceSearchAttributeArgs | NamespaceSearchAttributeState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NamespaceSearchAttributeState | undefined;
            resourceInputs["name"] = state?.name;
            resourceInputs["namespaceId"] = state?.namespaceId;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as NamespaceSearchAttributeArgs | undefined;
            if (args?.namespaceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'namespaceId'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["namespaceId"] = args?.namespaceId;
            resourceInputs["type"] = args?.type;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NamespaceSearchAttribute.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NamespaceSearchAttribute resources.
 */
export interface NamespaceSearchAttributeState {
    /**
     * The name of the search attribute.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The ID of the namespace to which this search attribute belongs.
     */
    namespaceId?: pulumi.Input<string | undefined>;
    /**
     * The type of the search attribute. Must be one of `bool`, `datetime`, `double`, `int`, `keyword`, `keywordList` or `text`. (case-insensitive)
     */
    type?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a NamespaceSearchAttribute resource.
 */
export interface NamespaceSearchAttributeArgs {
    /**
     * The name of the search attribute.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The ID of the namespace to which this search attribute belongs.
     */
    namespaceId: pulumi.Input<string>;
    /**
     * The type of the search attribute. Must be one of `bool`, `datetime`, `double`, `int`, `keyword`, `keywordList` or `text`. (case-insensitive)
     */
    type: pulumi.Input<string>;
}
