// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provisions a Temporal Cloud namespace.
 *
 * Regions available in Temporal Cloud: https://docs.temporal.io/cloud/regions.
 *
 * Note that regions are prefixed with the cloud provider (aws-us-east-1, not us-east-1)
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * Namespace can be imported to incorporate existing Namespaces into your Terraform pipeline.
 * To import a Namespace, you need
 * - a resource configuration in your Terraform configuration file/module to accept the imported Namespace. In the example below, the placeholder is "temporalcloud.Namespace" "terraform"
 * - the Namespace ID, which includes the Namespace Name and Account ID available at the top of the Namespace's page in the Temporal Cloud UI. In the example below, this is namespaceid.acctid
 *
 * ```sh
 * $ pulumi import temporalcloud:index/namespace:Namespace terraform namespaceid.acctid
 * ```
 */
export class Namespace extends pulumi.CustomResource {
    /**
     * Get an existing Namespace resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NamespaceState, opts?: pulumi.CustomResourceOptions): Namespace {
        return new Namespace(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'temporalcloud:index/namespace:Namespace';

    /**
     * Returns true if the given object is an instance of Namespace.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Namespace {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Namespace.__pulumiType;
    }

    /**
     * The Base64-encoded CA cert in PEM format that clients use when authenticating with Temporal Cloud. This is a required field when a Namespace uses mTLS authentication.
     */
    declare public readonly acceptedClientCa: pulumi.Output<string | undefined>;
    /**
     * If true, Temporal Cloud will enable API key authentication for this namespace.
     */
    declare public readonly apiKeyAuth: pulumi.Output<boolean>;
    /**
     * The capacity configuration for the namespace.
     */
    declare public readonly capacity: pulumi.Output<outputs.NamespaceCapacity | undefined>;
    /**
     * A list of filters to apply to client certificates when initiating a connection Temporal Cloud. If present, connections will only be allowed from client certificates whose distinguished name properties match at least one of the filters. Empty lists are not allowed, omit the attribute instead.
     */
    declare public readonly certificateFilters: pulumi.Output<outputs.NamespaceCertificateFilter[] | undefined>;
    /**
     * A codec server is used by the Temporal Cloud UI to decode payloads for all users interacting with this namespace, even if the workflow history itself is encrypted.
     */
    declare public readonly codecServer: pulumi.Output<outputs.NamespaceCodecServer | undefined>;
    /**
     * The IDs of the connectivity rules for this namespace.
     */
    declare public readonly connectivityRuleIds: pulumi.Output<string[] | undefined>;
    /**
     * The endpoints for the namespace.
     */
    declare public /*out*/ readonly endpoints: pulumi.Output<outputs.NamespaceEndpoints>;
    /**
     * The name of the namespace. Must be 2-64 characters, start with a letter, contain only lowercase letters, numbers, and hyphens, and not end with a hyphen.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The lifecycle configuration for the namespace. Note that this is different from the Terraform resource lifecycle. This controls settings like delete protection within Temporal Cloud.
     */
    declare public readonly namespaceLifecycle: pulumi.Output<outputs.NamespaceNamespaceLifecycle | undefined>;
    /**
     * The list of regions where this namespace is available. Must be one or two regions. See https://docs.temporal.io/cloud/regions for a list of available regions and HA options. Note that regions are prefixed with the cloud provider (aws-us-east-1, not us-east-1). If two regions are specified, the namespace will be replicated across them in a high availability (HA) configuration. Same-region, multi-region, and multi-cloud HA namespaces are supported. Please note that changing, adding, or removing regions for an existing namespace is not currently supported and the provider will throw an error. For HA namespaces the provider will ignore order changes on regions, which can happen if the namespace fails over.
     */
    declare public readonly regions: pulumi.Output<string[]>;
    /**
     * The number of days to retain workflow history. Any changes to the retention period will be applied to all new running workflows.
     */
    declare public readonly retentionDays: pulumi.Output<number>;
    declare public readonly timeouts: pulumi.Output<outputs.NamespaceTimeouts | undefined>;

    /**
     * Create a Namespace resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NamespaceArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NamespaceArgs | NamespaceState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NamespaceState | undefined;
            resourceInputs["acceptedClientCa"] = state?.acceptedClientCa;
            resourceInputs["apiKeyAuth"] = state?.apiKeyAuth;
            resourceInputs["capacity"] = state?.capacity;
            resourceInputs["certificateFilters"] = state?.certificateFilters;
            resourceInputs["codecServer"] = state?.codecServer;
            resourceInputs["connectivityRuleIds"] = state?.connectivityRuleIds;
            resourceInputs["endpoints"] = state?.endpoints;
            resourceInputs["name"] = state?.name;
            resourceInputs["namespaceLifecycle"] = state?.namespaceLifecycle;
            resourceInputs["regions"] = state?.regions;
            resourceInputs["retentionDays"] = state?.retentionDays;
            resourceInputs["timeouts"] = state?.timeouts;
        } else {
            const args = argsOrState as NamespaceArgs | undefined;
            if (args?.regions === undefined && !opts.urn) {
                throw new Error("Missing required property 'regions'");
            }
            if (args?.retentionDays === undefined && !opts.urn) {
                throw new Error("Missing required property 'retentionDays'");
            }
            resourceInputs["acceptedClientCa"] = args?.acceptedClientCa;
            resourceInputs["apiKeyAuth"] = args?.apiKeyAuth;
            resourceInputs["capacity"] = args?.capacity;
            resourceInputs["certificateFilters"] = args?.certificateFilters;
            resourceInputs["codecServer"] = args?.codecServer;
            resourceInputs["connectivityRuleIds"] = args?.connectivityRuleIds;
            resourceInputs["name"] = args?.name;
            resourceInputs["namespaceLifecycle"] = args?.namespaceLifecycle;
            resourceInputs["regions"] = args?.regions;
            resourceInputs["retentionDays"] = args?.retentionDays;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["endpoints"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Namespace.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Namespace resources.
 */
export interface NamespaceState {
    /**
     * The Base64-encoded CA cert in PEM format that clients use when authenticating with Temporal Cloud. This is a required field when a Namespace uses mTLS authentication.
     */
    acceptedClientCa?: pulumi.Input<string | undefined>;
    /**
     * If true, Temporal Cloud will enable API key authentication for this namespace.
     */
    apiKeyAuth?: pulumi.Input<boolean | undefined>;
    /**
     * The capacity configuration for the namespace.
     */
    capacity?: pulumi.Input<inputs.NamespaceCapacity | undefined>;
    /**
     * A list of filters to apply to client certificates when initiating a connection Temporal Cloud. If present, connections will only be allowed from client certificates whose distinguished name properties match at least one of the filters. Empty lists are not allowed, omit the attribute instead.
     */
    certificateFilters?: pulumi.Input<pulumi.Input<inputs.NamespaceCertificateFilter>[] | undefined>;
    /**
     * A codec server is used by the Temporal Cloud UI to decode payloads for all users interacting with this namespace, even if the workflow history itself is encrypted.
     */
    codecServer?: pulumi.Input<inputs.NamespaceCodecServer | undefined>;
    /**
     * The IDs of the connectivity rules for this namespace.
     */
    connectivityRuleIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The endpoints for the namespace.
     */
    endpoints?: pulumi.Input<inputs.NamespaceEndpoints | undefined>;
    /**
     * The name of the namespace. Must be 2-64 characters, start with a letter, contain only lowercase letters, numbers, and hyphens, and not end with a hyphen.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The lifecycle configuration for the namespace. Note that this is different from the Terraform resource lifecycle. This controls settings like delete protection within Temporal Cloud.
     */
    namespaceLifecycle?: pulumi.Input<inputs.NamespaceNamespaceLifecycle | undefined>;
    /**
     * The list of regions where this namespace is available. Must be one or two regions. See https://docs.temporal.io/cloud/regions for a list of available regions and HA options. Note that regions are prefixed with the cloud provider (aws-us-east-1, not us-east-1). If two regions are specified, the namespace will be replicated across them in a high availability (HA) configuration. Same-region, multi-region, and multi-cloud HA namespaces are supported. Please note that changing, adding, or removing regions for an existing namespace is not currently supported and the provider will throw an error. For HA namespaces the provider will ignore order changes on regions, which can happen if the namespace fails over.
     */
    regions?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The number of days to retain workflow history. Any changes to the retention period will be applied to all new running workflows.
     */
    retentionDays?: pulumi.Input<number | undefined>;
    timeouts?: pulumi.Input<inputs.NamespaceTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a Namespace resource.
 */
export interface NamespaceArgs {
    /**
     * The Base64-encoded CA cert in PEM format that clients use when authenticating with Temporal Cloud. This is a required field when a Namespace uses mTLS authentication.
     */
    acceptedClientCa?: pulumi.Input<string | undefined>;
    /**
     * If true, Temporal Cloud will enable API key authentication for this namespace.
     */
    apiKeyAuth?: pulumi.Input<boolean | undefined>;
    /**
     * The capacity configuration for the namespace.
     */
    capacity?: pulumi.Input<inputs.NamespaceCapacity | undefined>;
    /**
     * A list of filters to apply to client certificates when initiating a connection Temporal Cloud. If present, connections will only be allowed from client certificates whose distinguished name properties match at least one of the filters. Empty lists are not allowed, omit the attribute instead.
     */
    certificateFilters?: pulumi.Input<pulumi.Input<inputs.NamespaceCertificateFilter>[] | undefined>;
    /**
     * A codec server is used by the Temporal Cloud UI to decode payloads for all users interacting with this namespace, even if the workflow history itself is encrypted.
     */
    codecServer?: pulumi.Input<inputs.NamespaceCodecServer | undefined>;
    /**
     * The IDs of the connectivity rules for this namespace.
     */
    connectivityRuleIds?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The name of the namespace. Must be 2-64 characters, start with a letter, contain only lowercase letters, numbers, and hyphens, and not end with a hyphen.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * The lifecycle configuration for the namespace. Note that this is different from the Terraform resource lifecycle. This controls settings like delete protection within Temporal Cloud.
     */
    namespaceLifecycle?: pulumi.Input<inputs.NamespaceNamespaceLifecycle | undefined>;
    /**
     * The list of regions where this namespace is available. Must be one or two regions. See https://docs.temporal.io/cloud/regions for a list of available regions and HA options. Note that regions are prefixed with the cloud provider (aws-us-east-1, not us-east-1). If two regions are specified, the namespace will be replicated across them in a high availability (HA) configuration. Same-region, multi-region, and multi-cloud HA namespaces are supported. Please note that changing, adding, or removing regions for an existing namespace is not currently supported and the provider will throw an error. For HA namespaces the provider will ignore order changes on regions, which can happen if the namespace fails over.
     */
    regions: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The number of days to retain workflow history. Any changes to the retention period will be applied to all new running workflows.
     */
    retentionDays: pulumi.Input<number>;
    timeouts?: pulumi.Input<inputs.NamespaceTimeouts | undefined>;
}
