// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provisions a namespace export sink.
 */
export class NamespaceExportSink extends pulumi.CustomResource {
    /**
     * Get an existing NamespaceExportSink resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NamespaceExportSinkState, opts?: pulumi.CustomResourceOptions): NamespaceExportSink {
        return new NamespaceExportSink(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'temporalcloud:index/namespaceExportSink:NamespaceExportSink';

    /**
     * Returns true if the given object is an instance of NamespaceExportSink.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NamespaceExportSink {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NamespaceExportSink.__pulumiType;
    }

    /**
     * A flag indicating whether the export sink is enabled or not.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * The GCS configuration details when destinationType is GCS.
     */
    declare public readonly gcs: pulumi.Output<outputs.NamespaceExportSinkGcs | undefined>;
    /**
     * The namespace under which the sink is configured, formatted as `<namespace>.<account_id>`
     */
    declare public readonly namespace: pulumi.Output<string>;
    /**
     * The S3 configuration details when destinationType is S3.
     */
    declare public readonly s3: pulumi.Output<outputs.NamespaceExportSinkS3 | undefined>;
    /**
     * The unique name of the export sink, it can't be changed once set.
     */
    declare public readonly sinkName: pulumi.Output<string>;
    declare public readonly timeouts: pulumi.Output<outputs.NamespaceExportSinkTimeouts | undefined>;

    /**
     * Create a NamespaceExportSink resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NamespaceExportSinkArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NamespaceExportSinkArgs | NamespaceExportSinkState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NamespaceExportSinkState | undefined;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["gcs"] = state?.gcs;
            resourceInputs["namespace"] = state?.namespace;
            resourceInputs["s3"] = state?.s3;
            resourceInputs["sinkName"] = state?.sinkName;
            resourceInputs["timeouts"] = state?.timeouts;
        } else {
            const args = argsOrState as NamespaceExportSinkArgs | undefined;
            if (args?.namespace === undefined && !opts.urn) {
                throw new Error("Missing required property 'namespace'");
            }
            if (args?.sinkName === undefined && !opts.urn) {
                throw new Error("Missing required property 'sinkName'");
            }
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["gcs"] = args?.gcs;
            resourceInputs["namespace"] = args?.namespace;
            resourceInputs["s3"] = args?.s3;
            resourceInputs["sinkName"] = args?.sinkName;
            resourceInputs["timeouts"] = args?.timeouts;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NamespaceExportSink.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NamespaceExportSink resources.
 */
export interface NamespaceExportSinkState {
    /**
     * A flag indicating whether the export sink is enabled or not.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * The GCS configuration details when destinationType is GCS.
     */
    gcs?: pulumi.Input<inputs.NamespaceExportSinkGcs | undefined>;
    /**
     * The namespace under which the sink is configured, formatted as `<namespace>.<account_id>`
     */
    namespace?: pulumi.Input<string | undefined>;
    /**
     * The S3 configuration details when destinationType is S3.
     */
    s3?: pulumi.Input<inputs.NamespaceExportSinkS3 | undefined>;
    /**
     * The unique name of the export sink, it can't be changed once set.
     */
    sinkName?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.NamespaceExportSinkTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a NamespaceExportSink resource.
 */
export interface NamespaceExportSinkArgs {
    /**
     * A flag indicating whether the export sink is enabled or not.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * The GCS configuration details when destinationType is GCS.
     */
    gcs?: pulumi.Input<inputs.NamespaceExportSinkGcs | undefined>;
    /**
     * The namespace under which the sink is configured, formatted as `<namespace>.<account_id>`
     */
    namespace: pulumi.Input<string>;
    /**
     * The S3 configuration details when destinationType is S3.
     */
    s3?: pulumi.Input<inputs.NamespaceExportSinkS3 | undefined>;
    /**
     * The unique name of the export sink, it can't be changed once set.
     */
    sinkName: pulumi.Input<string>;
    timeouts?: pulumi.Input<inputs.NamespaceExportSinkTimeouts | undefined>;
}
