// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Manages the complete set of tags for a Temporal Cloud namespace.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as temporalcloud from "@pulumi/temporalcloud";
 *
 * // Create a namespace first
 * const example = new temporalcloud.Namespace("example", {
 *     name: "example-namespace",
 *     regions: ["aws-us-west-2"],
 *     apiKeyAuth: true,
 *     retentionDays: 14,
 * });
 * // Basic namespace tags example, with a custom timeout
 * const exampleNamespaceTags = new temporalcloud.NamespaceTags("example", {
 *     namespaceId: example.id,
 *     tags: {
 *         environment: "production",
 *         team: "backend",
 *         project: "temporal-workflows",
 *     },
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * Namespace Tags can be imported to incorporate existing Namespace Tags into your Terraform pipeline.
 * To import Namespace Tags, you need:
 * - a resource configuration in your Terraform configuration file/module to accept the imported Namespace Tags. In the example below, the placeholder is "temporalcloud.NamespaceTags" "tagsImport"
 * - the Namespace ID, which includes the Namespace Name and Account ID available at the top of the Namespace's page in the Temporal Cloud UI. In the example below, this is namespaceid.acctid
 *   The import ID format is: namespaceid.acctid/tags
 *
 * ```sh
 * $ pulumi import temporalcloud:index/namespaceTags:NamespaceTags tags_import namespaceid.acctid/tags
 * ```
 */
export class NamespaceTags extends pulumi.CustomResource {
    /**
     * Get an existing NamespaceTags resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NamespaceTagsState, opts?: pulumi.CustomResourceOptions): NamespaceTags {
        return new NamespaceTags(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'temporalcloud:index/namespaceTags:NamespaceTags';

    /**
     * Returns true if the given object is an instance of NamespaceTags.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NamespaceTags {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NamespaceTags.__pulumiType;
    }

    /**
     * The ID of the namespace to manage tags for.
     */
    declare public readonly namespaceId: pulumi.Output<string>;
    /**
     * A map of tag keys to tag values.
     */
    declare public readonly tags: pulumi.Output<{[key: string]: string}>;
    declare public readonly timeouts: pulumi.Output<outputs.NamespaceTagsTimeouts | undefined>;

    /**
     * Create a NamespaceTags resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NamespaceTagsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NamespaceTagsArgs | NamespaceTagsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NamespaceTagsState | undefined;
            resourceInputs["namespaceId"] = state?.namespaceId;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["timeouts"] = state?.timeouts;
        } else {
            const args = argsOrState as NamespaceTagsArgs | undefined;
            if (args?.namespaceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'namespaceId'");
            }
            if (args?.tags === undefined && !opts.urn) {
                throw new Error("Missing required property 'tags'");
            }
            resourceInputs["namespaceId"] = args?.namespaceId;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["timeouts"] = args?.timeouts;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NamespaceTags.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NamespaceTags resources.
 */
export interface NamespaceTagsState {
    /**
     * The ID of the namespace to manage tags for.
     */
    namespaceId?: pulumi.Input<string | undefined>;
    /**
     * A map of tag keys to tag values.
     */
    tags?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    timeouts?: pulumi.Input<inputs.NamespaceTagsTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a NamespaceTags resource.
 */
export interface NamespaceTagsArgs {
    /**
     * The ID of the namespace to manage tags for.
     */
    namespaceId: pulumi.Input<string>;
    /**
     * A map of tag keys to tag values.
     */
    tags: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    timeouts?: pulumi.Input<inputs.NamespaceTagsTimeouts | undefined>;
}
