// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provisions a Temporal Cloud Nexus endpoint.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as temporalcloud from "@pulumi/temporalcloud";
 *
 * const targetNamespace = new temporalcloud.Namespace("target_namespace", {
 *     name: "terraform-target-namespace",
 *     regions: ["aws-us-west-2"],
 *     apiKeyAuth: true,
 *     retentionDays: 14,
 * });
 * const callerNamespace = new temporalcloud.Namespace("caller_namespace", {
 *     name: "terraform-caller-namespace",
 *     regions: ["aws-us-east-1"],
 *     apiKeyAuth: true,
 *     retentionDays: 14,
 * });
 * const callerNamespace2 = new temporalcloud.Namespace("caller_namespace_2", {
 *     name: "terraform-caller-namespace-2",
 *     regions: ["gcp-us-central1"],
 *     apiKeyAuth: true,
 *     retentionDays: 14,
 * });
 * const nexusEndpoint = new temporalcloud.NexusEndpoint("nexus_endpoint", {
 *     name: "terraform-nexus-endpoint",
 *     description: `Service Name:
 *   my-hello-service
 * Operation Names:
 *   echo
 *   say-hello
 *
 * Input / Output arguments are in the following repository:
 * https://github.com/temporalio/samples-go/blob/main/nexus/service/api.go
 * `,
 *     workerTarget: {
 *         namespaceId: targetNamespace.id,
 *         taskQueue: "terraform-task-queue",
 *     },
 *     allowedCallerNamespaces: [
 *         callerNamespace.id,
 *         callerNamespace2.id,
 *     ],
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * Nexus Endpoints can be imported to incorporate existing Nexus Endpoints into your Terraform pipeline.
 * To import a Nexus Endpoint, you need
 * - a resource configuration in your Terraform configuration file/module to accept the imported Nexus Endpoint. In the example below, the placeholder is "temporalcloud.NexusEndpoint" "nexusEndpoint"
 * - the Nexus Endpoint's ID, which is found using the Temporal Cloud CLI tcld nexus endpoint list. In the example below, this is 405f7da4224a43d99c211904ed9b3819
 *
 * ```sh
 * $ pulumi import temporalcloud:index/nexusEndpoint:NexusEndpoint nexus_endpoint 405f7da4224a43d99c211904ed9b3819
 * ```
 */
export class NexusEndpoint extends pulumi.CustomResource {
    /**
     * Get an existing NexusEndpoint resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NexusEndpointState, opts?: pulumi.CustomResourceOptions): NexusEndpoint {
        return new NexusEndpoint(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'temporalcloud:index/nexusEndpoint:NexusEndpoint';

    /**
     * Returns true if the given object is an instance of NexusEndpoint.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NexusEndpoint {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NexusEndpoint.__pulumiType;
    }

    /**
     * Namespace Id(s) that are allowed to call this Endpoint.
     */
    declare public readonly allowedCallerNamespaces: pulumi.Output<string[]>;
    /**
     * The description for the Nexus endpoint.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The name of the endpoint. Must be unique within an account and match `^[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9]$`
     */
    declare public readonly name: pulumi.Output<string>;
    declare public readonly timeouts: pulumi.Output<outputs.NexusEndpointTimeouts | undefined>;
    /**
     * A target spec for routing nexus requests to a specific cloud namespace worker.
     */
    declare public readonly workerTarget: pulumi.Output<outputs.NexusEndpointWorkerTarget>;

    /**
     * Create a NexusEndpoint resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NexusEndpointArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NexusEndpointArgs | NexusEndpointState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NexusEndpointState | undefined;
            resourceInputs["allowedCallerNamespaces"] = state?.allowedCallerNamespaces;
            resourceInputs["description"] = state?.description;
            resourceInputs["name"] = state?.name;
            resourceInputs["timeouts"] = state?.timeouts;
            resourceInputs["workerTarget"] = state?.workerTarget;
        } else {
            const args = argsOrState as NexusEndpointArgs | undefined;
            if (args?.allowedCallerNamespaces === undefined && !opts.urn) {
                throw new Error("Missing required property 'allowedCallerNamespaces'");
            }
            if (args?.workerTarget === undefined && !opts.urn) {
                throw new Error("Missing required property 'workerTarget'");
            }
            resourceInputs["allowedCallerNamespaces"] = args?.allowedCallerNamespaces;
            resourceInputs["description"] = args?.description ? pulumi.secret(args.description) : undefined;
            resourceInputs["name"] = args?.name;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["workerTarget"] = args?.workerTarget;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["description"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(NexusEndpoint.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NexusEndpoint resources.
 */
export interface NexusEndpointState {
    /**
     * Namespace Id(s) that are allowed to call this Endpoint.
     */
    allowedCallerNamespaces?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The description for the Nexus endpoint.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The name of the endpoint. Must be unique within an account and match `^[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9]$`
     */
    name?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.NexusEndpointTimeouts | undefined>;
    /**
     * A target spec for routing nexus requests to a specific cloud namespace worker.
     */
    workerTarget?: pulumi.Input<inputs.NexusEndpointWorkerTarget | undefined>;
}

/**
 * The set of arguments for constructing a NexusEndpoint resource.
 */
export interface NexusEndpointArgs {
    /**
     * Namespace Id(s) that are allowed to call this Endpoint.
     */
    allowedCallerNamespaces: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The description for the Nexus endpoint.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The name of the endpoint. Must be unique within an account and match `^[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9]$`
     */
    name?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.NexusEndpointTimeouts | undefined>;
    /**
     * A target spec for routing nexus requests to a specific cloud namespace worker.
     */
    workerTarget: pulumi.Input<inputs.NexusEndpointWorkerTarget>;
}
