// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provisions a Temporal Cloud Project. Projects are an upcoming feature and may not be enabled for your account; contact Temporal support to request access.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as temporalcloud from "@pulumi/temporalcloud";
 *
 * const payments = new temporalcloud.Project("payments", {
 *     displayName: "payments",
 *     description: "Namespaces and resources owned by the Payments team.",
 *     projectLifecycle: {
 *         enableDeleteProtection: false,
 *     },
 * });
 * ```
 *
 * ## Import
 *
 * The `pulumi import` command can be used, for example:
 *
 * Projects can be imported to incorporate existing Projects into your Terraform pipeline.
 * To import a Project, you need
 * - a resource configuration in your Terraform configuration file/module to accept the imported Project. In the example below, the placeholder is "temporalcloud.Project" "projectimport"
 * - the Project's ID. In the example below, this is 8d1e3f2b0c9a4d5e8f7a6b5c4d3e2f10
 *
 * ```sh
 * $ pulumi import temporalcloud:index/project:Project projectimport 8d1e3f2b0c9a4d5e8f7a6b5c4d3e2f10
 * ```
 */
export class Project extends pulumi.CustomResource {
    /**
     * Get an existing Project resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProjectState, opts?: pulumi.CustomResourceOptions): Project {
        return new Project(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'temporalcloud:index/project:Project';

    /**
     * Returns true if the given object is an instance of Project.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Project {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Project.__pulumiType;
    }

    /**
     * The description of the Project.
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * The display name of the Project.
     */
    declare public readonly displayName: pulumi.Output<string>;
    /**
     * The lifecycle configuration for the Project. Note that this is different from the Terraform resource lifecycle. This controls settings like delete protection within Temporal Cloud.
     */
    declare public readonly projectLifecycle: pulumi.Output<outputs.ProjectProjectLifecycle | undefined>;
    /**
     * The current state of the Project.
     */
    declare public /*out*/ readonly state: pulumi.Output<string>;
    declare public readonly timeouts: pulumi.Output<outputs.ProjectTimeouts | undefined>;

    /**
     * Create a Project resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProjectArgs | ProjectState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProjectState | undefined;
            resourceInputs["description"] = state?.description;
            resourceInputs["displayName"] = state?.displayName;
            resourceInputs["projectLifecycle"] = state?.projectLifecycle;
            resourceInputs["state"] = state?.state;
            resourceInputs["timeouts"] = state?.timeouts;
        } else {
            const args = argsOrState as ProjectArgs | undefined;
            if (args?.displayName === undefined && !opts.urn) {
                throw new Error("Missing required property 'displayName'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["projectLifecycle"] = args?.projectLifecycle;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["state"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Project.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Project resources.
 */
export interface ProjectState {
    /**
     * The description of the Project.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The display name of the Project.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * The lifecycle configuration for the Project. Note that this is different from the Terraform resource lifecycle. This controls settings like delete protection within Temporal Cloud.
     */
    projectLifecycle?: pulumi.Input<inputs.ProjectProjectLifecycle | undefined>;
    /**
     * The current state of the Project.
     */
    state?: pulumi.Input<string | undefined>;
    timeouts?: pulumi.Input<inputs.ProjectTimeouts | undefined>;
}

/**
 * The set of arguments for constructing a Project resource.
 */
export interface ProjectArgs {
    /**
     * The description of the Project.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * The display name of the Project.
     */
    displayName: pulumi.Input<string>;
    /**
     * The lifecycle configuration for the Project. Note that this is different from the Terraform resource lifecycle. This controls settings like delete protection within Temporal Cloud.
     */
    projectLifecycle?: pulumi.Input<inputs.ProjectProjectLifecycle | undefined>;
    timeouts?: pulumi.Input<inputs.ProjectTimeouts | undefined>;
}
